### ISSUE TITLE
Filter Data State View

### ISSUE THREAD

**Issue by sosensible** [vuejs/vue-devtools#259] opened 2017-02-17 16:21 UTC
When looking at the data state, and changing something on the page I have to drill down again to get the state item I am watching. ( pain point )

Wouldn't it be cool if we could select, or filter down to the state level? Then when interacting with the app it would stay focused (when possible) on that level in the state data tree?

**Comment by posva** [comment] 2017-02-17 21:27
duplicate of #252

**Closed by posva** 2017-02-17 21:27 UTC
