### ISSUE TITLE
I can't see any content in devtools

### ISSUE THREAD

**Issue by hakuna0829** [vuejs/vue-devtools#1309] opened 2020-11-13 16:35 UTC
### Version
6.0.0-beta.2

### Browser and OS info
Google chrome Version 86.0.4240.193/Windows 10

### Steps to reproduce
After run my vue project on browser and go to vue devtool console, then it doesn't work at all.

### What is expected?
I want to see and use it normally.

### What is actually happening?
I can see error on browser dev console.

Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at Object.registerApp (backend.js:1204)

**Comment by hakuna0829** [comment] 2020-11-13 16:38
https://www.loom.com/share/4804db704eef4470b2703f736e0f11c1

**Comment by tosinek** [comment] 2020-11-18 18:51
Doesnt work for me either, the console error is 
```
Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at Object.registerApp (backend.js:1204)
registerApp @ backend.js:1204
async function (async)
registerApp @ backend.js:1191
initBackend @ backend.js:520
async function (async)
initBackend @ backend.js:514
handshake @ backend.js:1501
postMessage (async)
o @ proxy.js:1
291 @ proxy.js:1
n @ proxy.js:1
(anonymous) @ proxy.js:1
(anonymous) @ proxy.js:1
backend.js:570 Uncaught TypeError: Cannot read property 'id' of null
    at Bridge.<anonymous> (backend.js:570)
    at Bridge.emit (backend.js:3998)
    at Bridge._emit (backend.js:903)
    at backend.js:835
    at Array.forEach (<anonymous>)
    at backend.js:835
    at listener (backend.js:1477)
```
I use Firefox as a workaround as that still uses version 5.3.3

**Comment by tosinek** [comment] 2020-11-18 18:54
duplicate of https://github.com/vuejs/vue-devtools/issues/1289

**Comment by limruby** [comment] 2020-12-15 19:42
Exactly the same problem:

`DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/shared-data.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`
`backend.js:1204 Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at Object.registerApp (backend.js:1204)`
`Uncaught TypeError: Cannot read property 'id' of null
    at Bridge.<anonymous> (backend.js:570)
    at Bridge.emit (backend.js:3998)
    at Bridge._emit (backend.js:903)
    at backend.js:835
    at Array.forEach (<anonymous>)
    at backend.js:835
    at listener (backend.js:1477)`

**Comment by Akryum** [comment] 2021-01-29 10:53
Duplicate of #1289

**Closed by Akryum** 2021-01-29 10:53 UTC

**Comment by SlitiBrahim** [comment] 2021-03-30 10:14
I was using `vue x2.6` and `@vue/devtools` version `^6.0.0-beta.6` in a content-script chrome extension and that did not worked thent I replaced `@vue/devtools` with version `^5.3.4` and now it's working, I have my components displayed in the vuedevtools app !
