### ISSUE TITLE
Vuex store not getting updated with Nuxt

### ISSUE THREAD

**Issue by Angelostr** [vuejs/vue-devtools#935] opened 2019-03-28 09:41 UTC
### Version
5.0.3

### Browser and OS info
Chrome on Windows 10

### Steps to reproduce

After updating to the latest vue devtools version 5.0.3 version, the Vuex store is not getting updated. This was working fine in previous vue devtools version.
Here is the code I’m using in store/index.js

export const state = () => ({
    categories: []
})

export const mutations = {
    SET_CATEGORIES (state, categories) {
        state.categories = categories
    }
}

export const actions = {
    async nuxtServerInit({ commit }) {
        let response = await this.$axios.$get('categories')

        commit('SET_CATEGORIES', response.data)
    }
}

### What is expected?
I only see an empty 'categories' array when inspecting in the Vuex store. This worked fine in previous devtools version.
I'm expecting the Vuex store array to get updated as seen in previous versions

### What is actually happening?
I only see an empty 'categories' array when inspecting in the Vuex store. This worked fine in previous devtools version.
I'm expecting the Vuex store array to get updated as seen in previous versions

**Comment by Akryum** [comment] 2019-03-28 13:55
Please provide a runnable reproduction.

**Comment by MaxKostenko** [comment] 2019-03-28 14:18
Probably problem only when it used together with Nuxt. 

It doesn't display state that was generated on server side. Instead it show initial state.
But it will show relevant state if you come to page from client side (when you change route).
Also if you in Enable dev mode in chrome extension it will cache store state when you open page first times  and always display it.

**Comment by MaxKostenko** [comment] 2019-03-28 14:29
Basic example of vuex for Nuxt display incorrect info in devtools https://8y075vn9w0.sse.codesandbox.io/

**Comment by akosipax** [comment] 2019-03-28 17:12
I also have this issue and it doesn't use Nuxt. I'll try to provide a runnable reproduction.

**Comment by chanmathew** [comment] 2019-03-28 17:22
Also having this issue, using Dev tools 5.0.4 and Nuxt 2.5.1

**Comment by vedmant** [comment] 2019-03-29 03:42
I have the same issue, I need to open and close chrome dev tools to make it load vuex state again.

**Comment by akosipax** [comment] 2019-03-30 12:37
I cannot reproduce the problem anymore since #940 was fixed.

**Comment by JFGHT** [comment] 2019-04-01 08:24
I'm in 5.0.6 and still having this issue.

**Comment by chanmathew** [comment] 2019-04-02 04:53
^ that could be why I’m having the same issue, I’m using Object.assign to modify the state object.

**Comment by Akryum** [comment] 2019-04-04 15:03
@joezoller It will not work because the mutations payload is cloned so we can replay them.

**Comment by joezoller** [comment] 2019-04-04 15:38
@Akryum Hrm, unfortunate in my case (recursive tree traversal) that the sum of the parts doesn't equal the whole, but not the end of the world.  Thanks for taking a look.

**Comment by mrleblanc101** [comment] 2019-04-08 19:17
Not fixed. I'm using nuxt with vue-dev-tools 5.0.8

**Closed** 2019-04-09 20:17 UTC
Labels: bug

**Comment by mrleblanc101** [comment] 2019-04-11 02:58
Yes, this fixed it for Nuxt ! Thanks

**Comment by mgdodge** [comment] 2019-06-03 20:06
Not working in Nuxt for me using minimal SPA generated by create-nuxt-app and the following store:
```
export const state = () => ({
  counter: 0
})

export const mutations = {
  increment (state) {
    state.counter++
  }
}
```
Tried latest (5.1.0), as well as a few older versions (5.0.8 and 5.0.2). None worked. Going all the way back to the latest 4.x release (4.1.5 beta) worked fine.

**Comment by canhkieu** [comment] 2019-11-14 10:33
It's not work again. :(

**Comment by tiagomatosweb** [comment] 2019-12-02 22:59
I'm having the same issue. My vuex devtools suddenly got empty

**Comment by Valentin-Seehausen** [comment] 2020-03-08 04:00
Having the same issue with the latest versions and config.vue.devtools = true.

**Comment by Valentin-Seehausen** [comment] 2020-03-08 04:23
Erm... ok that sounds very silly:

It works now. I had to turn on recording. The small red button on top of the commit list of devtools.

Don't know why and when I turned it off. Sorry. :-D

**Comment by stouch** [comment] 2020-03-17 18:30
Didn't work for me, even with turning on "recording"...

**Comment by AdamBD** [comment] 2020-03-26 14:47
I'm having this same issue when using Vue. Components which have deps for data from VueX only have reactivity when the vue-devtools is open. If I have chrome devtools closed reactivity does not work.

**Comment by AlexandroWillianHervis** [comment] 2020-05-17 15:10
I'm having the same issue.

**Comment by dimoreira** [comment] 2020-05-21 03:50
Same here. I can't even dispatch the load state actions from `nuxtServerInit` function. The store don't update neither.

**Comment by TheDeveloperTom** [comment] 2020-09-08 14:16
The problem is actual @yyx990803

**Comment by arnauddsj** [comment] 2020-09-21 05:29
I've got the same problem, with nuxt but not sure it comes from nuxt.
i use a custom vuelidate validation on a fiels that check if a url is unique.
if not I commit the error to vuex.
and i show the error in my component.

`const isUnique = async function(value) {
	// check if not already user address
	if (this.lib.user.url !== value) {
		try {
			const urlStatus = await LibService.checkUrl(value)
			this.$store.commit("stat/RESET_ERROR")
			return urlStatus
		} catch (err) {
			// send error to vuex
			this.$store.commit("stat/SET_ERROR", {
				message: "Adresse déjà utilisée",
				target: "url"
			})
			return false
		}
	} else {
		return true
	}
}`

when ever I type an already used url nothing happens until I open vue devtools, and then magically everything is working again... If I uninstall vue devtools the problem is still here and I found no way to make the error appear.

**Comment by affinage-digital** [comment] 2020-09-25 07:30
I've got the same problem. Vuex state randomly updated or not from nuxtServerInit

**Comment by ed3899** [comment] 2021-03-20 15:38
Same here! Not working on Brave, using Nuxt

**Comment by sniperadmin** [comment] 2021-08-01 06:17
upvoting this, not working here too

**Comment by immrakpk** [comment] 2021-08-08 15:33
Same .......... 
State
export const state = () => ({
  categories: null,
  categories_products: [],
})
Mutations
  POPULATE_CATEGORIES_PRODUCTS(state, product_obj) {
    state.categories_products.push(product_obj)
  },

ACTIONS
export const actions = {
    async delete_prod_action({commit}, slug) {
        await this.$axios.$delete("/products/prods" + `/${slug}`)
        commit('DELETE_PROD', slug)
    },
    async nuxtServerInit(store, {$axios}) {
        

        this.$store_helpers.print()
        try {
            // 1 -  Get categories list by calling url
            const categories_get_res = await $axios.$get("/products/categories/")
            
            // 2 -  Add categories list to store 
            store.commit('POPULATE_CATEGORIES', categories_get_res.results)

            // // 3 -  Construct categories_products structure
            let categories_products_objs = this.$store_helpers.create_category_objs(categories_get_res.results)

            } catch (error) { console.log(error)}

        // -  Popuplate Categories Products
        for (let i=0; i<store.state.categories.length; i++){
            $axios.$get(`/products/prods/category/${store.state.categories[i].name}/`)
            .then((response)=>{
                if(response.results){
                    var temp_obj = {}
                    // store.state.categories_products
                    temp_obj.name = store.state.categories[i].name
                    temp_obj.products_list = []
                    store.commit('POPULATE_CATEGORIES_PRODUCTS',temp_obj)
                }
                else{
                    var temp_obj = {}
                    temp_obj.name = store.state.categories[i].name
                    temp_obj.products_list = []
                    console.log(response.length)
                    for (const elem in response){
                        temp_obj.products_list.push(response[elem])
                    }
                    console.log(temp_obj.products_list)
                    store.commit('POPULATE_CATEGORIES_PRODUCTS',temp_obj)
                }
            })
        }

    }

}

store.commit('POPULATE_CATEGORIES_PRODUCTS',temp_obj) ### **DOES NOT WORK**

Simple update yet spent hours does not work.

**Comment by bear30921** [comment] 2021-09-14 11:57
same issue.

nuxt 2.15.7
