### ISSUE TITLE
Menu is broken

### ISSUE THREAD

**Issue by beardcoder** [vuejs/vue-devtools#1112] opened 2019-11-15 08:42 UTC
### Version
5.3.2

### Browser and OS info
macOS 10.15.2 with Brave 1.0

### Steps to reproduce
1. Install Vue devtools in Brave
2. Open dev tools on a vue application in dev mode
3. Click on the "Settings" menu item or the "Performance" menu icon
4. Try to click on other items => not work 

### What is expected?
As user i can select all menu items

### What is actually happening?
After i select the settings item i can nothing do

**Comment by beardcoder** [comment] 2019-11-15 09:08
I have tryed to fix the error. 
The problem is the local storage access in Brave. This is restricted for extensions by default.

**Comment by tmvst** [comment] 2019-11-15 09:45
I have the same problem. Is there any way to enable local storage for extensions in Brave? Or any other workaround until it's fixed?

**Comment by DKhalil** [comment] 2019-11-20 08:33
I submitted a PR #1102 to fix this but so far haven't gotten any response, @Akryum any possibility to merge this?

**Comment by Akryum** [comment] 2019-11-25 16:00
Duplicate of #1097

**Closed by Akryum** 2019-11-25 16:00 UTC
