### ISSUE TITLE
Excuse me. How do I view components cached through keep-alive?

### ISSUE THREAD

**Issue by codon19** [vuejs/vue-devtools#1412] opened 2021-04-22 08:19 UTC
### What problem does this feature solve?
vue3
Vue.js devtools 6.0.0 beta 7

Now I have no idea which components are cached and which are not

### What does the proposed API look like?
Hopefully it's the same as Vue2 devtools

**Comment by Akryum** [comment] 2021-04-22 16:13
Duplicate of #1411

**Closed by Akryum** 2021-04-22 16:13 UTC
