### ISSUE TITLE
Console drawer not shown in Vue tab

### ISSUE THREAD

**Issue by dodalovic** [vuejs/vue-devtools#485] opened 2017-12-29 19:43 UTC
Hi, there :)
In all other tabs in dev-tools, when I keep pressing `esc` key - console drawer pops up / down.
In *Vue* tab that's not the case - it just kind of flickers the screen. 

Chrome: `Version 63.0.3239.108 (Official Build) (64-bit)`
MacOS: `10.13.2 (17C88)`

By design?
Thanks & keep doing great job!

**Comment by posva** [comment] 2017-12-31 12:43
Duplicate of #426

**Closed by posva** 2017-12-31 12:43 UTC
