### ISSUE TITLE
Why read my browsing history?

### ISSUE THREAD

**Issue by Handsome2734** [vuejs/vue-devtools#498] opened 2018-01-13 03:36 UTC
Why devtools need to read my browsing history?
What's the point of this?
![devtools](https://user-images.githubusercontent.com/5567825/34902427-08aba1b8-f856-11e7-869b-9c2c61049c11.png)

**Comment by daniilr** [comment] 2018-01-13 06:27
This is a duplicate of #493

**Closed** 2018-01-13 08:41 UTC
