### ISSUE TITLE
Extension fires onerror on all web pages, crashes web apps

### ISSUE THREAD

**Issue by AshleyScirra** [vuejs/vue-devtools#565] opened 2018-01-25 12:38 UTC
### Version
4.1.0

### Browser and OS info
Any

### Steps to reproduce
Installing Vue.js dev tools throws this error in a `contextmenu` event:

```
Uncaught ReferenceError: o is not defined
    at HTMLDocument.document.addEventListener.t (<anonymous>:1:784)
```

The distributed code looks like this:

```js
document.addEventListener("contextmenu", t=>{
        const n = t.target;
        if (n) {
            const t = Object(o.a)(n);
            if (t)
                return e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = !0,
                void (e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = t)
        }
        e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = null,
        e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = null
    }
```

The throwing line is `Object(o.a)(n)` which appears to correspond to `findRelatedComponent(el)` here: https://github.com/vuejs/vue-devtools/blob/2df80656476bd039fe49a2f4f9c0f579fc9c8845/src/backend/index.js#L739
The issue is `o` is not declared anywhere.

It even reproduces on https://vuejs.org/ - just right click and look in the browser console.

This is really bad news for any web apps that listen to the onerror handler. In our web app Construct 3, we show a crash dialog and terminate the user's session any time onerror happens. So any user who has this extension and uses our web app will see a crash as soon as they right click. (See original report to us here: https://github.com/Scirra/Construct-3-bugs/issues/1238) Further, it spams our error logging analytics engine with a lot of reports that are nothing to do with our code.

### What is expected?
Extension should never produce unhandled errors.

### What is actually happening?
Extension produces unhandled errors which brings down web apps.

**Comment by yGuy** [comment] 2018-01-25 13:54
That's really bad - ideally all plugin code should run in a huge try/catch, because this kind of programming errors makes a lot of pages go mad. I thought our products had a new bug, too, when we suddenly received many of these weird exceptions.

**Comment by Akryum** [comment] 2018-01-25 13:55
Duplicate of #514

**Closed by Akryum** 2018-01-25 13:55 UTC
