### ISSUE TITLE
Vuex panel does not update on store.register/unregisterModule()

### ISSUE THREAD

**Issue by davestewart** [vuejs/vue-devtools#657] opened 2018-04-02 10:58 UTC
### Version
4.1.4

### Browser and OS info
Mac OSX 10.12.6 / Chrome 65.0.3325.181

### Steps to reproduce

```js
// register module
app.$store.registerModule('test', {
  namespaced: true,
  state: {
    value: 1
  },
  mutations: {
    value: (state, value) => state.value = value
  }
})

// wait, and check devtools vuex panel

// commit  mutation and see dev panel update
app.$store.commit('test/value', 100)
```

### What is expected?
Maybe there's some reason for this, but I would expect the vuex panel to update with the new store module as the module is registered / unregistered

### What is actually happening?
The vuex panel only updates when a mutation (to any module or value) is committed

**Comment by lossendae** [comment] 2018-06-02 23:52
Not sure if it's the same bug, but the registerModule does show the module in the console, but it's not removed when unregisterModule is called.

I have to reload the console (twice F12) to see the updated store

**Comment by alajfit** [comment] 2018-06-26 16:24
this is still a problem, when registering modules they don't appear in the console until you reload the frame

**Comment by Akryum** [comment] 2018-07-25 14:48
Duplicate of #282

**Closed by Akryum** 2018-07-25 14:48 UTC
Labels: enhancement, pri:low
