### ISSUE TITLE
Do not show store4x

### ISSUE THREAD

**Issue by yoonasy** [vuejs/vue-devtools#1389] opened 2021-03-26 09:20 UTC
### Version
6.0.0-beta.7

### Browser and OS info
Chrome  89.0.4389.90 / Windows 10

### Steps to reproduce
```
app.use(ElementPlus, { locale })
app.use(store) // this is use store, Do not show store state data in vue-devtools
app.use(router)
app.config.globalProperties.$elToImg = elToImg
app.config.globalProperties.$copy = copy
app.mount('#app')
```

### What is expected?
show store4x state data

### What is actually happening?
Do not show store4x

![image](https://user-images.githubusercontent.com/24489180/112610014-30fb3300-8e57-11eb-88b2-244c6ae55fd2.png)
![image](https://user-images.githubusercontent.com/24489180/112610075-407a7c00-8e57-11eb-91e1-55bcb02efc6a.png)

**Comment by Akryum** [comment] 2021-03-26 10:44
Duplicate of #1268

**Closed by Akryum** 2021-03-26 10:44 UTC

**Comment by splifted** [comment] 2021-03-27 01:28
Stop
