### ISSUE TITLE
Cannot set property '__VUE_DEVTOOLS_UID__' of null

### ISSUE THREAD

**Issue by hjdrent** [vuejs/vue-devtools#1289] opened 2020-10-02 14:50 UTC
### Version
6.0.0-beta.2

### Browser and OS info
Chrome 85.0.4183.121/Windows 10 

### Steps to reproduce
Open a simple VUE project. Open Developer Tools. Goto VUE tab. Find components

### What is expected?
the components on the page

### What is actually happening?
No components found.
Errormessage: Cannot set property '__VUE_DEVTOOLS_UID__' of null

**Comment by lyahim** [comment] 2020-10-04 12:38
+1

**Comment by lyahim** [comment] 2020-10-04 12:42
![image](https://user-images.githubusercontent.com/3195083/95015870-c4456f80-064f-11eb-87df-ff52d405b737.png)

**Comment by skaesdorf** [comment] 2020-10-06 01:08
I have exactly the same problem. Even with a completely fresh project with vue-router, vuex and vuetify via vue-cli (Didn't test without plugins) . The problem is, that the plugin fails to detect the root instance since there is no handler for the eventType "getAppRootInstance" available when calling "backendOn.callHandlers" and "pluginOn.callHandlers" in backend.js

```
backend.js (1199): await ctx.api.getAppRootInstance(options.app) //problematic call starts here
backend.js (144): payload = await backendOn.callHandlers(eventType, payload, ctx); //no handler for "getAppRootInstance"
backend.js (145): payload = await pluginOn.callHandlers(eventType, payload, ctx); //no handler for "getAppRootInstance"
```

Would appreciate a fix for this

Cheers
Stefan

**Comment by raukaute** [comment] 2020-10-26 14:32
I encounter the same problem when creating an app instance with `createSSRApp` and as far as I can see, my problem results not from a missing handler for getAppRootInstance, but from the handler not 'finding' the root instance. It is checking for `_vnode` property on the app root container which in turn gets added in the mount phase. This, yet another turn, only happens when using `createApp`.

**Comment by stiltet** [comment] 2020-10-29 09:56
I'm having the same issue.. The normal Vue Devtools is crashing constantly without error and when updating to beta I can't use it at all... For me I can't use any of them witch is making debugging very time consuming and tricky.

**Comment by tosinek** [comment] 2020-11-18 18:54
You can use firefox as that still uses version 5.3.3

**Comment by stiltet** [comment] 2020-11-18 19:05
Yeah. The problem with that is that the app I’m working on atm is an internal tool that only works in Chrome. I ended up downgrading but that version keeps crashing and then I need to restart Chrome to get it back up. I’m handling it through classical JS debugging most of the times but it for sure would ease up my life if I could get a more stable version working.

**Comment by alanwilhelm** [comment] 2020-12-24 18:40
![image](https://user-images.githubusercontent.com/175353/103103145-536d7e00-45d4-11eb-8888-ee7011a98848.png)
Same mess. 

PS: When do we get Vuex devtools back?

**Comment by RUSHt** [comment] 2021-01-01 13:22
Me too !

**Comment by langlangbody** [comment] 2021-01-06 03:05
Me too !   in 6.0.0-beta.3

**Comment by apo1967** [comment] 2021-01-07 11:55
Same here with 6.0.0 beta 3 and Vue 2 app

**Comment by mckrava** [comment] 2021-01-12 11:35
Look's like dev tools `6.0.0 beta 3` works correct only with Vue3 apps. I've installed beta version because stable version doesn't work with Vue 3 apps. So now I cannot use beta with Vue 2 apps. Perfect update )))

**Comment by JesLopezS** [comment] 2021-01-27 16:05
got the same in chrome, but I used Mozilla and there is no problem, maybe it's a chrome bug
I'm using Firefox Developer  Edition

**Comment by brokenthorn** [comment] 2021-01-27 19:08
I noticed nobody mentioned Microsoft Edge. I'm experiencing the same issue on Edge Version 88.0.705.50 (Official build) (64-bit) on macOS Big Sur 11.1 build 20C69.

**Comment by Akryum** [comment] 2021-01-29 11:24
Please make sure you don't have the stable devtools (v5.x) enabled at the same time.

**Comment by Akryum** [comment] 2021-02-01 00:47
Currently the devtools 6.x beta doesn't support Vue 1 and Vue 2 yet. Please use the stable version if you want to inspect a Vue 1 or Vue 2 app.

**Comment by NickEastNL** [comment] 2021-02-08 23:10
I can confirm that this error also occurs when using `createSSRApp` in combination with server-side rendering. Although there's currently a lack of documentation for doing SSR with Vue 3, the few examples I found used this new method to create the Vue app on both the server and the client (through the universal code). Hydration also seems to only work when doing this, so this must be a bug. However, I'm not sure whether this is a bug in Dev Tools (for not differentiating between the two createApp methods), or Vue 3 itself (that `createSSRApp` is not creating the Vue instance correctly).

**Comment by bubbakk** [comment] 2021-02-16 09:20
Have the same problem with v. 6.0.0 beta 6 and a fresh Nuxt.js + Vue.js installation.

**Comment by Akryum** [comment] 2021-02-16 15:18
@bubbakk Nuxt currently uses Vue 2.

**Comment by desys-tambellini** [comment] 2021-02-16 16:57
Same error for me, but with latest version of Vite and with the ssr test project https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue

**Comment by sidelong44** [comment] 2021-02-22 23:20
Same problem with version 6.0.0 beta 7

**Comment by wwwizzarrdry** [comment] 2021-02-25 18:12
> Currently the devtools 6.x beta doesn't support Vue 1 and Vue 2 yet. Please use the stable version if you want to inspect a Vue 1 or Vue 2 app.

This was my issue. I had the extension from the beta channel installed. When I fired up a project with Quasar (Vue 2) the extension failed. Removing the beta and installing the stable extension resolved the issue. Thanks for the info.

**Comment by jsonwu5** [comment] 2021-03-05 06:01
Same problem with version 6.0.0 beta 7, but when I lowered the version to 5.2.0, it worked!

**Comment by Akryum** [comment] 2021-03-05 09:21
> Currently the devtools 6.x beta doesn't support Vue 1 and Vue 2 yet. Please use the stable version if you want to inspect a Vue 1 or Vue 2 app.

**Closed by Akryum** 2021-03-05 09:21 UTC
Labels: v6
