### ISSUE TITLE
Error "Cannot read property 'type' of null" after update to 4.0.1

### ISSUE THREAD

**Issue by ezhkov** [vuejs/vue-devtools#516] opened 2018-01-15 13:31 UTC
### Version
4.0.0

### Browser and OS info
Chrome 63.0.3239.132, Firefox 57.0.4 / MacOS High Sierra

### Steps to reproduce
1. Open any web page containing vue component
2. Open Vue devtools 4.0.1
3. Click to any component

### What is expected?
Component is selected. 
I can see all data and props

### What is actually happening?
Component data not available.
Have an error in the console.
"Cannot read property 'type' of null." in Crome
"TypeError: o is null" - in Firefox

**Comment by trrete** [comment] 2018-01-15 13:36
Me too, I'm having the same problem!

**Comment by posva** [comment] 2018-01-15 13:37
Probably a duplicate of #507 
Could you please provide a boiled down repro in an HTML file or a github repo?

**Comment by dhulme** [comment] 2018-01-15 13:49
Are you using vee-validate? After updating to 2.0.3 the issue was resolved for me.
https://github.com/vuejs/vue-devtools/issues/499#issuecomment-357506247

**Comment by trrete** [comment] 2018-01-15 13:50
Yes I also update vee-validate and now it works!

**Comment by ronnibaslund** [comment] 2018-01-15 14:02
I also update vee-validate and now it works!

**Closed** 2018-01-15 14:07 UTC
Labels: need repro

**Comment by studamanabtech** [comment] 2018-01-15 18:47
thank you 👍  its working now
