### ISSUE TITLE
v4.0.0 Requires "Browser History" permission.

### ISSUE THREAD

**Issue by AbhishekBiswal** [vuejs/vue-devtools#502] opened 2018-01-13 13:17 UTC
v4.0.0 by default was disabled on chrome (after update) because it required a new permission : "Browser History". I don't see any reason for this change, and I can see a lot of users complaining on the chrome store review page as well.

**Comment by Samuell1** [comment] 2018-01-13 13:22
https://github.com/vuejs/vue-devtools/pull/500

**Comment by Akryum** [comment] 2018-01-13 13:30
Duplicate of #493

**Closed by Akryum** 2018-01-13 13:30 UTC
Labels: duplicate
