### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by jq-87** [vuejs/vue-devtools#552] opened 2018-01-24 20:33 UTC
### Version
4.1.0

### Browser and OS info
Chrome 63 / OSX 10.12.6

### Steps to reproduce
this started happening today 1/24/17.

When toggling between vue dev tools and the chrome console, the console is saying:
backend.js:1 - Uncaught TypeError: Cannot read property 'classList' of null

I've cleared out all my js and this error still appears.

### What is expected?
This error should not show - it is not from my code

### What is actually happening?
There is an error from vue dev tools in my browser console

---
I'm using Vue.js version 2.5.11

**Comment by Akryum** [comment] 2018-01-24 20:44
We need a minimal reproduction.

**Comment by anteriovieira** [comment] 2018-01-24 20:57
@Akryum this same error happened to me. I would like to help by providing a replay to find the problem. But I do not know the way to do this, could you help me?

**Comment by anteriovieira** [comment] 2018-01-24 21:00
I think it's associated with [this line](https://github.com/vuejs/vue-devtools/blob/842aa3572d76446732cc8dae5e7a98731b7f1e15/src/devtools/env.js#L26).

**Comment by anteriovieira** [comment] 2018-01-24 21:16
Steps to reproduce the error:
- Open the application in the browser. `http://localhost:8080`
- Open the devtools
- Select the vue tab
- Select the console tab
- Refresh the page

> I could not reproduce the error using vue-devtools as the development environment.  `npm run dev:chrome`

**Comment by taylorotwell** [comment] 2018-01-24 21:49
I can also confirm error happening to me on latest tools.

**Comment by conoramanatullah** [comment] 2018-01-24 21:55
I am also seeing the same issue.

**Comment by Pilfer** [comment] 2018-01-24 21:59
Confirming that it's an issue for me as well.

Version 63.0.3239.132 (Official Build) (64-bit)
Latest version of devtools.

Is anyone else getting an uncaught reference area when right clicking/using the context menu?

![image](https://user-images.githubusercontent.com/3060203/35359334-b347ec4c-0127-11e8-93bd-5697f366c257.png)


Associated with:

```
{const t=Object(o.a)(n);if(t)return e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__=!0,void(e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__=t)}e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__=null,e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__=null})})```

**Comment by anteriovieira** [comment] 2018-01-24 22:01
Fixed in https://github.com/vuejs/vue-devtools/pull/554

**Comment by tgosp** [comment] 2018-01-24 22:09
@anteriovieira - looks good for me. Can we release and deploy now?

It's not super critical, but for example if you place new component somewhere in the page, you have to close and open again dev tools to see it. Only page refresh / hoc don't show new components in components list for me.

**Comment by nasirouwagana** [comment] 2018-01-24 22:10
@Pilfer, actually I have a same issue

**Closed** 2018-01-24 22:27 UTC
Labels: need repro

**Comment by Odaeus** [comment] 2018-01-26 09:47
Sorry to pester but this seems to have quite a big impact? My Vue devtools pane frequently "freezes" after I see this error in the console. Would it be possible to release this as 4.1.1 quickly?

**Comment by LinusBorg** [comment] 2018-01-26 09:53
> Would it be possible to release this as 4.1.1 quickly?

4.1.1 is already out since yesterday.

![image](https://user-images.githubusercontent.com/1444526/35434282-eba87448-0286-11e8-9c0d-fea98b9d9990.png)

If the problem persists with 4.1.1, please open a new issue.

**Comment by nasirouwagana** [comment] 2018-01-26 10:01
The problem is solved. Thank you.

**Comment by Odaeus** [comment] 2018-01-26 10:14
My apologies, I was looking at this repository for the version to update (which [was done](https://github.com/vuejs/vue-devtools/commit/d5b8a753b64d48704200d9bde34e66303022c8c1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) a few minutes after my comment).

**Comment by LinusBorg** [comment] 2018-01-26 10:24
That's what happens when you quikcly push an important update ;)
