### ISSUE TITLE
Unable to install in Firefox

### ISSUE THREAD

**Issue by Tarasovych** [vuejs/vue-devtools#992] opened 2019-05-07 09:04 UTC
### Version
5.1.0

### Browser and OS info
Firefox 66.0.3 (64-bit) / Ubuntu 18.04

### Steps to reproduce
- Open https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/
- Click "Add to Firefox"

### What is expected?
Addon installation

### What is actually happening?
Error message "Download failed. Please check your connection."

---
Addon dissapeared once I opened the browser, can't install it back now. No such problem with any other addons.

**Comment by Akryum** [comment] 2019-05-07 11:03
Duplicate of #989

**Closed by Akryum** 2019-05-07 11:03 UTC
