### ISSUE TITLE
TypeError: Cannot read property 'instanceMap' of undefined

### ISSUE THREAD

**Issue by Doeke** [vuejs/vue-devtools#1453] opened 2021-05-27 13:55 UTC
### Version
6.0.0-beta.11

### Browser and OS info
Chrome 90 / Linux

### Steps to reproduce
Open my app with vue devtools enabled

### What is expected?
No error

### What is actually happening?
    backend.js:991 Uncaught (in promise) TypeError: Cannot read property 'instanceMap' of undefined
    at getComponentInstance (backend.js:991)
    at Object.sendSelectedComponentData (backend.js:935)
    at Object.<anonymous> (backend.js:1211)
    at Object.emit (<anonymous>:1:755)
    at DevtoolsPluginApiInstance.notifyComponentUpdate (backend.js:381)

**Comment by Akryum** [comment] 2021-05-27 17:17
Duplicate of #1451

**Closed by Akryum** 2021-05-27 17:17 UTC
