### ISSUE TITLE
Update sent to component rendering the slot instead of the component passing the slot

### ISSUE THREAD

**Issue by glennraya** [vuejs/vue-devtools#1404] opened 2021-04-15 07:14 UTC
### Version
6.0.0-beta.7

### Browser and OS info
Chrome v90

### Steps to reproduce
Open vue-dev tools (beta 6) bind input using v-model as usual, then if you try to type something, the property on data {} is not updating on the vue-dev tools.

### What is expected?
Property in data() {} should be updating when value is changed. It's properly bound using v-model

### What is actually happening?
The property is not updating unless you select other components then selecting the component again.

**Comment by glennraya** [comment] 2021-05-09 09:15
> On 6.0.0-beta.9 all is working fine, so possibly might be closed.

It's still the same on beta 9 (at least on my side), I have to click the component to see the changes to the vue-devtools inspector. :(

**Comment by iraklisg** [comment] 2021-05-14 09:08
Hello All

I am having the same problem. The issue basically occurs when the input component is wrapped in another component that exposes a slot.

Here is a reproduction link: https://github.com/iraklisg/vue-3-dev-tools

In the `App` component the  `inputs.bar` ref property is updated in dev-tools as expected. However, the `inputs.foo` does not update since it is slotted via `FormSection` component. 
In addition, typing on the inputs.bar input triggers inputs.foo property to update

I am using `v6.0.0-beta.10` on Firefox Developer edition 89.0b6 (64-bit) - OS Linux

**Comment by Akryum** [comment] 2021-05-19 16:20
Fixed in vue 3 repository

**Closed by Akryum** 2021-05-19 16:20 UTC
Labels: bug, v6

**Comment by iraklisg** [comment] 2021-05-22 16:55
@Akryum thank you. Should we expect to see the fix with the next Vue 3 release (3.0.12) ?

**Comment by Akryum** [comment] 2021-05-22 17:30
3.1 beta 4 should be released on Monday, will see if we do a patch to 3.0
