### ISSUE TITLE
Match dark theme colors to fit native browser colors when selecting auto theme

### ISSUE THREAD

**Issue by septatrix** [vuejs/vue-devtools#1089] opened 2019-10-23 12:05 UTC
### What problem does this feature solve?
The vue-devtools do not match the native browser colors of chrome when using the dark devtools theme.
Instead they use the colors from @vue/ui. These vibrant dark black and blue colors however clash strongly with the muted gray one is used to from the native devtools.
For the end user the vue-devtools extensions therefore feels out of place.

### What does the proposed API look like?
I propose to overwrite the default background, header and border color from @vue/ui when using vue-devtools auto dark theme. This can easily be done as there are only about five places where we would need to overwrite the styles.
Optionally the @vue/ui color scheme could still be made available under the settings panel.

**Comment by septatrix** [comment] 2019-10-23 12:06
Comparison of the custom dark scheme used by vue-devtools to a proposed dark theme fitting the native dark theme of the chrome devtools

![Screenshot from 2019-10-23 13-39-24](https://user-images.githubusercontent.com/24257556/67391113-3c7d6700-f59e-11e9-97e1-0a221f1007cc.png)
![Screenshot from 2019-10-23 13-56-38](https://user-images.githubusercontent.com/24257556/67391114-3c7d6700-f59e-11e9-9209-f8dc7ff81466.png)

**Comment by Akryum** [comment] 2019-10-23 13:45
Duplicate of #913

**Closed by Akryum** 2019-10-23 13:45 UTC
