### ISSUE TITLE
Vue.js is not detected with vue@3.0.0-rc.4

### ISSUE THREAD

**Issue by zhuqingguang** [vuejs/vue-devtools#1244] opened 2020-07-25 07:00 UTC
Be patient.
> FYI: @Akryum is working on this. Please wait for the next release. 
>                                                                                   ——  From Evan
---------------------------------
### Version
6.0.0-beta.1

### Browser and OS info
版本 84.0.4147.89/ MacOS10.14.3

### Steps to reproduce
- install vue@3.0.0-rc.4  and run webpack-dev-server
- download vue-devtools in version of 6.0.0-beta.1

### What is expected?
Vue can be detected

### What is actually happening?
Vue.js is not detected 

---
I don't know it's a question of vue-devtools or vue-next. Could you point what should i do to use vue-devtools . Is something wrong in my project ?

**Comment by Uninen** [comment] 2020-07-26 09:43
Vue is also not detected when creating a new Vue 3 project w/ vuex and ue-router using the new vue-cli 4.5.0.

**Comment by BellemareMederic** [comment] 2020-08-01 01:30
Confirm that bugs
devtools version : 6.0.0 beta 1
"core-js": "^3.6.5",
"vue": "^3.0.0-rc.5",
"vue-router": "^4.0.0-beta.4"

have a not detected on the chrome extension and my files are not minify

**Comment by ThisIsRuddy** [comment] 2020-08-03 11:08
Same except 3.0.0-rc.5 :(

**Comment by yoyoys** [comment] 2020-08-05 04:31
I've tested with same result with 3.0.0-rc.5, but `__VUE_DEVTOOLS_GLOBAL_HOOK__.store` is detected.

```json
...
    "vue": "3.0.0-rc.5",
    "vue-router": "4.0.0-beta.5",
    "vuex": "4.0.0-beta.4"
    "@vue/compiler-sfc": "^3.0.0-rc.5",
    "vue-cli-plugin-vue-next": "~0.1.3"
    "core-js": "^3.6.5",
...
```

**Comment by d-pollard** [comment] 2020-08-06 13:40
Hoping this gets resolved; would love to start playing with the new features

**Comment by Rekodr** [comment] 2020-08-08 20:22
same issue with  3.0.0-rc.1,  ...,  3.0.0-rc.5 on both Chrome and FireFox. The standalone does not work either. Hope this to be fix soon.

**Comment by fkranenburg** [comment] 2020-08-11 20:16
Same issue here with latest 3.0.0-rc version. Would really like to play with 3.0.0. I just added `window.__VUE__ = true;` in my `main.js` to force make it accessible, and the devtools did start. But also then nothing is really working. Hope this is resolved soon.

**Comment by Yakoot** [comment] 2020-08-17 12:14
same issue

**Comment by bzd2000** [comment] 2020-08-17 12:19
indeed, it is really hard to test vue3 without the devtools working

**Comment by bzd2000** [comment] 2020-08-17 16:12
I don't manage to build it locally, something weird in the package.json I don't understand

**Comment by ThisIsRuddy** [comment] 2020-08-17 16:14
If its compilation your having issues with then this is not the thread for
you

**Comment by sodatea** [comment] 2020-08-18 14:34
I think it's fixed in Vue CLI 4.5.4 with this PR https://github.com/vuejs/vue-cli/pull/5788

If you are using the webpack template, please update the config accordingly.

**Comment by marcus-herrmann** [comment] 2020-08-18 15:03
> I think it's fixed in Vue CLI 4.5.4 with this PR vuejs/vue-cli#5788

Vue CLI 4.5.4 does not make any difference in my case:

```
"vue": "^3.0.0-rc.5",
"@vue/cli-service": "~4.5.4",
```

No dev tools pane in both Firefox (79) and Chrome (83)

**Comment by 9mm** [comment] 2020-08-20 02:12
I am trying to learn vue and i used vue-cli to make a new vue-3 project using the router option. I am using `yarn serve` for the server. It says `vue.js not found` in the vue chrome extension. Is this related? Im at a loss how to fix it. Thanks

**Comment by Zenemig** [comment] 2020-08-20 17:01
### Version
6.0.0-beta.1

### Browser and OS info
Google Chrome Version 86.0.4239.0 (Official Build) canary (x86_64)
MacOS Catalina 10.15.2

### Steps to reproduce
Create a Vue project using vue@3.0.0-rc.5 and run `npm run serve`
Download Vue Devtools version of 6.0.0-beta.1

### What is expected?
Vue is detected by the extension

### What is actually happening?
Vue is not detected

Just started a new project and when I got to a point where I needed Vue Devtools, turns out it's not working. Is there a fix on the works? I didn't see this referenced on any PRs.

**Comment by yyx990803** [comment] 2020-08-24 02:18
FYI: @Akryum is working on this. Please wait for the next release.

**Comment by stefaanv** [comment] 2020-08-28 06:40
Same problem here with `vue-cli 4.5.4` and typescript.
```
    "vue": "^3.0.0-0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
```

**Comment by byungster** [comment] 2020-09-01 03:40
Same too!
    "vue": "^3.0.0-0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0",
    "vuex-class": "^0.3.2",
    "vuex-module-decorators": "^0.17.0"

**Comment by euaaaio** [comment] 2020-09-01 10:29
Just build `next` brunch via `yarn && yarn build` command then manually add `packages/shell-chrome` folder to Chrome → Extensions → Developer mode → Load unpacked.

**Comment by Uninen** [comment] 2020-09-01 10:55
The manual build works for me but I haven't seen any version yet that would actually work in any meaningful way that would show any components or any other details from my app. The current build only shows an empty app with no components or data. I've tested this with four different Vue 3 projects, the same results with all of them.

**Comment by euaaaio** [comment] 2020-09-01 11:02
> The manual build works for me but I haven't seen any version yet that would actually work in any meaningful way that would show any components or any other details from my app. The current build only shows an empty app with no components or data. I've tested this with four different Vue 3 projects, the same results with all of them.

It already works.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/5614115/91841777-9ab5b480-ec5b-11ea-8099-9e1ffff1a573.png">

**Comment by Uninen** [comment] 2020-09-01 11:43
Re-tested just now. Interestingly the build from very latest commit doesn't show the Vue tab at all even though the extension loads ok and shows active on the projects. Tested with three different projects.

A build from a couple of commits back loads but for me doesn't show anything but a blank app and doesn't do anything. Haven't seen any functionality in any of my builds from the next branc ever in any of my Vue 3 projects. Using Chrome (85.0.4183.83) on macOS and Vue 3 RC9 w/ vue-router and TypeScript, with vue-cli and one test project with Vite.

All prjojects show up like this for me (I also have dark mode on but the plugin always loads bright version and haven't found a place for setting it from the new plugin as none of the tabs work properly):

<img width="882" alt="Screenshot 2020-09-01 at 14 34 35" src="https://user-images.githubusercontent.com/43100/91845121-4b728280-ec61-11ea-9af4-e25d3db037c7.png">

**Comment by Uninen** [comment] 2020-09-01 11:47
I also get this error (taken from Chrome extensions error tab) with first page load but it goes away with refresh. It still doesn't seem to affect in te behaviour at all, nothing shows up except a blank App.

<img width="667" alt="Screenshot 2020-09-01 at 14 45 24" src="https://user-images.githubusercontent.com/43100/91845521-fa16c300-ec61-11ea-9c85-0f5b9ca9479d.png">

**Comment by Uninen** [comment] 2020-09-01 12:19
Sorry for the comment spam but I got the plugin somewhat working after completely deleting and reinstalling Chrome. Found out that the problem was in my code which in all projects uses Suspend and async components. After removing these just for debugging purposes I now see a list of components:

<img width="978" alt="Screenshot 2020-09-01 at 15 11 01" src="https://user-images.githubusercontent.com/43100/91850286-f4bb7780-ec65-11ea-8744-8198d32b0715.png">

So the `Suspend`-component and `async setup` is not yet supported (or doesn't work properly) but a build from the next-branch kind-of works already indeed.

**Comment by Mehdi-Hp** [comment] 2020-09-02 16:12
Running `window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = app.constructor` makes Vue tab to appear, but empty.

![image](https://user-images.githubusercontent.com/8641684/92008769-cff5fb80-ed5c-11ea-9c6d-dd6a59decd73.png)

**Comment by Mehdi-Hp** [comment] 2020-09-06 13:59
Found a caveat. Make sure `vue-cli-plugin-vue-next` is **not** installed. Fixed my problem.

**Comment by ellisonpatterson** [comment] 2020-09-08 16:01
> 
> 
> Found a caveat. Make sure `vue-cli-plugin-vue-next` is **not** installed. Fixed my problem.

Fixes all issues, thank you!

**Comment by yoyoys** [comment] 2020-09-08 16:33
@Mehdi-Hp 
> Found a caveat. Make sure `vue-cli-plugin-vue-next` is **not** installed. Fixed my problem.

This breaks vuex and vue-router.

got message like that
```
Failed to compile with 7 errors                                        上午12:27:13

This dependency was not found:

* vue in ./node_modules/vue-router/dist/vue-router.esm.js, ./node_modules/vuex/dist/vuex.esm-browser.js and 5 others

To install it, you can run: npm install --save vue
No issues found.

```

**Comment by rajinder-yadav** [comment] 2020-09-10 20:38
Not working on Firefox also

**Comment by xSorc** [comment] 2020-09-11 07:01
This code works for me (Chrome + Vue 3.0.0-rc.10)

```js
// main.ts
import App from '@/App.vue';
import { devtools } from '@/devtools';
import router from '@/router';

createApp(App).use(devtools).use(router).mount('#app');

// devtools.ts
import { App, Plugin } from 'vue';

const devtools: Plugin = {
	install(app: App) {
		// @ts-ignore
		if (process.env.NODE_ENV === 'development' && window.__VUE_DEVTOOLS_GLOBAL_HOOK__) {
			// @ts-ignore
			window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = app;
		}
	},
};

export { devtools };
```

**Comment by ThisIsRuddy** [comment] 2020-09-12 20:41
Not sure what has changed but it seems to be working now as I have just created a fresh project via vue-cli and re-tested

`Chrome Extension: Vue DevTools 6.0.0 beta 2`

```
 "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-router": "4.0.0-beta.9"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "sass": "^1.26.10",
    "sass-loader": "^10.0.2"
  }
```
![screenshot](https://user-images.githubusercontent.com/1761171/93004637-9bdebf80-f540-11ea-8410-b99cfafc254b.png)

**Comment by 9mm** [comment] 2020-09-12 22:22
@ThisIsRuddy did you install it from github using the developer version of the extension instead of doing it from the chrome store? Maybe that is the problem

**Comment by 9mm** [comment] 2020-09-12 22:23
Ah-ha! Here's the beta channel for anyone interested: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg

**Comment by 9mm** [comment] 2020-09-12 22:24
Now it works, awesome. Thank you @ThisIsRuddy I'm glad you put the version of your extension or I would not have ever noticed.

**Comment by mkasprz** [comment] 2020-10-08 12:55
I also confirm that on Firefox a version from a beta channel works too. It's available here: https://github.com/vuejs/vue-devtools/releases . Thank You @9mm and others involved.

**Comment by lauri108** [comment] 2020-10-28 10:22
> Ah-ha! Here's the beta channel for anyone interested: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg

Thank you @9mm and @ThisIsRuddy, now works for me after installing that beta version of Vue devtools. My Vue3 app is being detected.

**Comment by mustafadalga** [comment] 2020-10-29 20:14
> Ah-ha! Here's the beta channel for anyone interested: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg

I solved the problem with vue.js devtools beta in vue cli 4.5.8 version.Thank you.

**Comment by BinaryBen** [comment] 2020-11-04 05:15
Not sure if related. I installed Vue Dev Tools and when I click the icon it tells me it can't find Vue on the page. I have the following dependencies:

```json
...
"vue": "^3.0.0",
"vue-router": "^4.0.0-0",
"vuex": "^4.0.0-0"
...
"@vue/cli-service": "~4.5.0",
```

Here is where it gets weird. I installed the beta channel, and now BOTH(!) say they can find vue on the page when I click the icon, but the panel never shows up in devtools. I have also tried disabling the stable channel extension, and the beta extension still says it can detect it but again, no panel. Same behaviour on Brave and Chrome (pretty unsurprising, but thought I would note in case it's of interest).

Thoughts?

**Comment by tony140407** [comment] 2020-11-10 07:22
> Not sure if related. I installed Vue Dev Tools and when I click the icon it tells me it can't find Vue on the page. I have the following dependencies:
> 
> ```json
> ...
> "vue": "^3.0.0",
> "vue-router": "^4.0.0-0",
> "vuex": "^4.0.0-0"
> ...
> "@vue/cli-service": "~4.5.0",
> ```
> 
> Here is where it gets weird. I installed the beta channel, and now BOTH(!) say they can find vue on the page when I click the icon, but the panel never shows up in devtools. I have also tried disabling the stable channel extension, and the beta extension still says it can detect it but again, no panel. Same behaviour on Brave and Chrome (pretty unsurprising, but thought I would note in case it's of interest).
> 
> Thoughts?

right click on vue-devtools icon
click "Manage Extensions"
check the "Allow access to file URLs"

It works for me
I hope this answers your questions.

**Comment by bryansray** [comment] 2020-11-13 03:50
For anyone else still having issues ... I had to remove my previous vue.js devtools extension (v5.x) to get the new extension to show up in my Chrome Dev Tools tab. I'm sure you can probably "disable" it as well. 

Hope that helps someone out. 🍀

**Comment by sgrubsmyon** [comment] 2020-11-16 18:47
Using version 6.0.0.2 of vue-devtools (v6.0.0-beta.2 installed from https://github.com/vuejs/vue-devtools/releases) in Firefox 82.0.3, when I open the Vue panel in Dev Tools (connecting to a Vue 3.0.2 app), I get an exception in the console:

```
Uncaught (in promise) TypeError: appRecord is undefined
    setupBuiltinLayers moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:2164
    emit eval:1
    _replayBuffer eval:1
    on eval:1
    setupBuiltinLayers moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:2162
    setupTimeline moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:2113
    connect moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:621
    n eval:1
    emit eval:1
    initBackend moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:531
    emit eval:1
    _replayBuffer eval:1
    on eval:1
    initBackend moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:529
    handshake moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1501
    262 moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1458
    __webpack_require__ moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:20
    <anonymous> moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:84
    <anonymous> moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:87
backend.js:2164:23
```

and 2 times:

```
App with id NaN not found 2 backend.js:561:21
    connect moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:561
    emit moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:3998
    _emit moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:903
    Bridge moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:835
    Bridge moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:835
    listener moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1477
    (Async: EventListener.handleEvent)
    listen moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1480
    Bridge moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:833
    handshake moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1473
    (Async: EventListener.handleEvent)
    262 moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:1458
    __webpack_require__ moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:20
    <anonymous> moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:84
    <anonymous> moz-extension://bf79a28c-5cbf-4da1-b16d-3bf83aad5179/build/backend.js:87
```

Anyone else seeing this?

**Comment by cb-adarsh** [comment] 2020-11-19 07:10
> For anyone else still having issues ... I had to remove my previous vue.js devtools extension (v5.x) to get the new extension to show up in my Chrome Dev Tools tab. I'm sure you can probably "disable" it as well.
> 
> Hope that helps someone out. 🍀

@bryansray Turns out having both normal and beta devtools causes the issue! I disabled the original vue devtools and beta devtools worked perfectly!!
FYI: i had to export devtools manually in my code, see [snippet link here](https://github.com/vuejs/vue-devtools/issues/1244#issuecomment-690915714)

**Comment by san-wi** [comment] 2020-12-03 13:14
> Be patient.
> 
> > FYI: @Akryum is working on this. Please wait for the next release.
> > ——  From Evan
> 
> ### Version
> 6.0.0-beta.1
> 
> ### Browser and OS info
> 版本 84.0.4147.89/ MacOS10.14.3
> 
> ### Steps to reproduce
> * install vue@3.0.0-rc.4  and run webpack-dev-server
> * download vue-devtools in version of 6.0.0-beta.1
> 
> ### What is expected?
> Vue can be detected
> 
> ### What is actually happening?
> Vue.js is not detected
> 
> I don't know it's a question of vue-devtools or vue-next. Could you point what should i do to use vue-devtools . Is something wrong in my project ?

### 可用的方法

```javascript
import { createApp } from 'vue'
import App from './App.vue'

const app = createApp(App)

// 分环境处理
if (process.env.NODE_ENV === 'development') {
  if ('__VUE_DEVTOOLS_GLOBAL_HOOK__' in window) {
  // 这里__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue赋值一个createApp实例
    window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = app
  }
}

app.mount('#app')
```
解决方法来自[vue-devtools README.md](https://github.com/vuejs/vue-devtools#force-enable-the-devtools)，之后对比了Vue2 window `__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue`

后面翻评论看到 @xSorc 已经解决了

**Comment by VottusCode** [comment] 2020-12-18 08:47
My current dependencies are the following:
```json
{
  "dependencies": {
    "autoprefixer": "^9",
    "axios": "^0.21.0",
    "bulma": "^0.9.1",
    "core-js": "^3.6.5",
    "epic-spinners": "^1.1.0",
    "postcss": "^7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
    "topbar": "^0.1.4",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vue3-click-away": "^1.1.0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^7.0.0-0",
    "lint-staged": "^9.5.0",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3"
  }
}
```

The project is working fine, without any issues. It has been migrated from Vue 2. With Vue 2, the devtools have worked, but after migrating to Vue 3 they stopped working.

I currently have the Vue.js devtools 6.0.0-beta2 and while they do work with new Vue 3 projects (created via Vue CLI), it does not work with ours. I have even went as far as removing anything except app.mount("#app") and the App.vue component only contained of one div, but to no avail.

**Comment by tomhave97** [comment] 2020-12-18 14:02
> > Ah-ha! Here's the beta channel for anyone interested: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg
> 
> Thank you @9mm and @ThisIsRuddy, now works for me after installing that beta version of Vue devtools. My Vue3 app is being detected.

You need to remove it completely. Also if you added it before removing the base one, romove both again and install the beta version. After that it should work. 😄

**Comment by VottusCode** [comment] 2020-12-28 17:00
To fix your issue, remove your `yarn.lock` (or `package-lock.json` in case of NPM) and install your dependencies again using the appropriate command.

**Comment by FavourOyewumi7** [comment] 2021-01-05 01:29
What works for me is when i installed both the beta and the former version

**Comment by EthanZeigler** [comment] 2021-01-17 04:36
> What works for me is when i installed both the beta and the former version , the only bad thing is the vue panel doesn't actually show

I had the same issue. You have to restart the browser when installing the beta devtools.

**Comment by FavourOyewumi7** [comment] 2021-01-18 02:36
oh thanks later got this

**Closed** 2021-01-29 11:43 UTC

**Comment by yashrathi-git** [comment] 2021-02-25 13:13
Switching to Vue.js devtools beta channel worked for me.
Remove the vue.js devtools extension and install the beta version.
Install it from here: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg/related

**Comment by jcrawford** [comment] 2021-03-12 01:58
> Switching to Vue.js devtools beta channel worked for me.
> Remove the vue.js devtools extension and install the beta version.
> Install it from here: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg/related

Thanks that worked for me as well :)

**Comment by nicooprat** [comment] 2021-03-21 10:00
I couldn't make devtools work with Vue 3 + Vite 2, for now I got this workaround in `main.js` ([based on previous comment](https://github.com/vuejs/vue-devtools/issues/1244#issuecomment-690915714)):

```js
const app = createApp(App)
if(import.meta.env.DEV && window.__VUE_DEVTOOLS_GLOBAL_HOOK__) {
  window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = app
}
app.mount('#app')
```

I might have missed something obvious but devtools were working fine with other Vue 3 +vue-cli, so I guess it's some kind of Vite incompatibility for now.

**Comment by LinusBorg** [comment] 2021-03-21 11:10
Devtools work fine for my Vite projects without any workarounds:

<img width="321" alt="Bildschirmfoto 2021-03-21 um 12 09 45" src="https://user-images.githubusercontent.com/1444526/111902567-64e0ed80-8a3e-11eb-952d-60d30b2c5b84.png">

**Comment by nicholasscottfish** [comment] 2021-03-29 00:04
For anyone still having this issue on Vue 3 projects:

- Install the beta version of Vue dev tools - https://v3.vuejs.org/guide/migration/introduction.html#devtools-extension
- Disable the stable version of the extension via chrome://extensions/
- For localhost urls you may need to edit the extension options and ensure "Allow access to file URLs" is enabled

When switching back to Vue 2 projects:

- Disable the beta version via chrome://extensions/
- Enable the stable version of the extension

**Note:** You may need to restart Chrome for the changes to take effect

**Comment by germsb** [comment] 2021-04-04 09:35
> Devtools work fine for my Vite projects without any workarounds:
> 
> <img alt="Bildschirmfoto 2021-03-21 um 12 09 45" width="321" src="https://user-images.githubusercontent.com/1444526/111902567-64e0ed80-8a3e-11eb-952d-60d30b2c5b84.png">


The vue tab appears fine but it's the only thing that works. Click on image to see video.  

[![Imgur](https://imgur.com/DQson6c.png)](https://youtu.be/Fy0ox5vRzik)

**Comment by lloydjatkinson** [comment] 2021-04-13 02:04
This also does not work for me. I have both versions of the Vue dev tools installed but no tab in F12.
![image](https://user-images.githubusercontent.com/5633938/114486036-f63e1c80-9c04-11eb-8a2b-7cfd3135489d.png)

**Comment by germsb** [comment] 2021-04-13 06:42
> > Devtools work fine for my Vite projects without any workarounds:
> > <img alt="Bildschirmfoto 2021-03-21 um 12 09 45" width="321" src="https://user-images.githubusercontent.com/1444526/111902567-64e0ed80-8a3e-11eb-952d-60d30b2c5b84.png">
> 
> The vue tab appears fine but it's the only thing that works. Click on image to see video.
> 
> [![Imgur](https://camo.githubusercontent.com/a5e6ece418b87443e0b3f7558817367e518ee51a002f0a5d7aebf74f3818dc27/68747470733a2f2f696d6775722e636f6d2f4451736f6e36632e706e67)](https://youtu.be/Fy0ox5vRzik)

Finally, I solved the problem by uninstalling chrome and deleting all the folders and files it leaves behind.  After reinstallation, the problem came back when I logged in to synchronize data from my Google account.  I had to turn off extension sync and some more stuff before everything was back to normal

**Comment by k0d3d** [comment] 2021-08-23 15:05
If using Vue 3, you need the new version of the extension that is currently still in beta https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en

**Comment by nolimitdev** [comment] 2021-11-24 09:22
New extension https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en seems to support also Vue 2 although website https://v3.vuejs.org/guide/migration/introduction.html#devtools-extension says that only Vue 3 is supported. The same with Router support (Vuex support not tested).

> The new version is currently in beta and only supports Vue 3 (for now). Vuex and Router integration is also work in progress.

**Comment by WhyNotHugo** [comment] 2022-01-20 21:00
The latest version of the addon still won't pick up Vue3 project. [The latest version](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) is from January 2021, so it seems it's still not been pushed to AMO?

**Comment by Akryum** [comment] 2022-01-20 23:52
Unfortunately Mozilla doesn't allow uploading beta versions of addons on AMO.

**Comment by WhyNotHugo** [comment] 2022-01-21 10:00
Oh, vue3 support is not yet stable?

**Comment by LinusBorg** [comment] 2022-01-21 10:18
It basically is, we just haven't done the switch yet, which we will be doing alongside the rest shortly:

https://blog.vuejs.org/posts/vue-3-as-the-new-default.html

**Comment by WhyNotHugo** [comment] 2022-01-21 10:36
Ah, thanks! I'd missed that there was a coordinated switch date. Looking forward to it.

**Comment by hussein12334** [comment] 2022-02-07 20:18
vue.js devtools just stopped working, no clue why just doesnt want to detect anything

**Comment by tomexsansdev** [comment] 2022-04-28 07:53
I Know this is Closed. In Case someone needs this to save you a lot of hair pulling.
When Using VueJS3 + Vite

Using the Version 6.1.4 of the FireFox DevTools Extension

Package.json
```
...
 "vue": "^3.2.31",
 "vue-chartjs": "^4.0.6",
 "vue-router": "^4.0.12",
  "@vitejs/plugin-vue": "^2.2.2",
  "@vitejs/plugin-vue-jsx": "^1.3.7",
  "@vue/eslint-config-prettier": "^7.0.0",
  "@vue/test-utils": "^2.0.0-rc.18"
...
```

You need to add it to the it to the Vite config

Vite.config.js
```
export default defineConfig({
  __VUE_PROD_DEVTOOLS__ : process.env.NODE_ENV === 'development'
})
```
