### ISSUE TITLE
Crash after page refresh

### ISSUE THREAD

**Issue by TheDiehard22** [vuejs/vue-devtools#594] opened 2018-01-30 16:21 UTC
### Version
4.1.2

### Browser and OS info
Chrome 64.0.3282.119, Windows 10 - version 1709

### Steps to reproduce
Open Vue devtools.
Switch to components or Vuex.
Refresh the page.
Try to click anything in the vue devtools, which does not respond.

### What is expected?
That the devtools extension is still responsive.

### What is actually happening?
It stops responding. The only way to make it work again is to press f12 and then f12 again and switch to the Vue tab. Only works till the next page refresh.

---
I restarted my PC.
I checked for the same behaviour in another project, which has the same behaviour.
The bug appeared since today, first values in Vuex were not updating and later the whole devtools became unresponsive after refresh.
A colleague has same the problem in a different project and Chrome 63.

**Comment by AnthonyPorthouse** [comment] 2018-01-30 16:25
Can reproduce on OS X

## Version
4.1.2

## Browser and OS info
Chrome 63.0.3239.132, Mac OS X 10.13.2

**Comment by Akryum** [comment] 2018-01-30 16:41
Duplicate of #588

**Closed by Akryum** 2018-01-30 16:41 UTC
