### ISSUE TITLE
Vuex state issue with registerModule

### ISSUE THREAD

**Issue by xereda** [vuejs/vue-devtools#875] opened 2019-02-04 12:40 UTC
### Version
5.0.0-beta.4

### Browser and OS info
Chrome 71.0.3578.98 64 bits / Arch Linux

### Steps to reproduce
In an app with store, access the Vuex tab.

### What is expected?
Access state data.

### What is actually happening?
The application crashes when we use version 5 beta 4.

---
Below are two simulations. One with version 4.1.5 and another with the new version 5.beta4.

version 5.beta.4:

![vue-devtools-5 beta 4](https://user-images.githubusercontent.com/14337850/52209040-c6976b00-2869-11e9-90ba-128fc51e0c3c.gif)

version 4.1.5:

![vue-devtools-4 1 5](https://user-images.githubusercontent.com/14337850/52209070-d7e07780-2869-11e9-8a60-f6a50d8ae008.gif)

**Comment by Akryum** [comment] 2019-02-04 13:20
Please try only enabling one version of the devtools at a time.

**Comment by Akryum** [comment] 2019-02-04 13:22
Also an actual runnable reproduction is needed.

**Comment by xereda** [comment] 2019-02-04 13:22
Yes I did it. I left the two enabled just to make it easier to burn the gif.

**Comment by xereda** [comment] 2019-02-04 15:25
I did a simulation of the same application. Each simulation with a unique and exclusive version of vue devtools. Note that in version 5.beta4, the state object is not displayed.

**Comment by xereda** [comment] 2019-02-04 15:40
The state object, as well as getters, does not appear in the new version:

![captura de tela de 2019-02-04 13-37-51](https://user-images.githubusercontent.com/14337850/52218775-7bd61d00-2882-11e9-85bf-1ab09d25032e.png)

![peek 04-02-2019 13-38](https://user-images.githubusercontent.com/14337850/52218784-7f69a400-2882-11e9-805b-037311d19db4.gif)

**Comment by wanxe** [comment] 2019-02-05 09:47
Same here! @xereda

**Comment by xereda** [comment] 2019-02-05 10:58
> Same here! @xereda
> I think that is a problem with the modules and async modules. Because if you test just with an "standard store" configuration it works fine.

I do not know if I understand. @wanxe 

You mean it's not working with namespace modules?

**Comment by Sp1ker** [comment] 2019-02-05 11:02
Can you create public repo with reproduction this problem?

**Comment by xereda** [comment] 2019-02-05 11:06
@Sp1ker The application depends on several features only available on our intranet.

**Comment by xereda** [comment] 2019-02-05 11:41
@Akryum I tried to simulate with a new project, with the vue cli, but there are no problems. Same namespaced modules added.

The point is that the entire set may be necessary. But this will not be possible to simulate outside of our intranet. There are dependencies of various services.

I'm really excited about vue devtools version 5 beta 4, but I think I'll stay out of it.

**Comment by xereda** [comment] 2019-02-05 11:43
No error occurs. Only it can not load the state. If I click on the first MUTATION of the timeline, the state is loaded. In others, it does not.

I use gifs because it is the closest way to simulate the situation for you.

**Comment by xereda** [comment] 2019-02-05 11:59
I know it's not the best scenario to test this, but that's what I can do.

I'll send as many details as I can.

Note the following gif. In the first mutation I have access to the state correctly. 
If I click on the other MUTATIONS, the state is not displayed.

![peek 05-02-2019 09-55](https://user-images.githubusercontent.com/14337850/52272067-bac0ad00-292c-11e9-960b-da2d8c7a3af2.gif)

**Comment by xereda** [comment] 2019-02-05 12:03
The error that appears in the console does not occur when I am using vue dev tools 4.1.5.

  I'll detail this error below. Maybe some detail will help.

![captura de tela de 2019-02-05 10-03-18](https://user-images.githubusercontent.com/14337850/52272238-476b6b00-292d-11e9-8ab5-dd7d4b4964a0.png)

**Comment by wanxe** [comment] 2019-02-05 12:12
> > Same here! @xereda
> > I think that is a problem with the modules and async modules. Because if you test just with an "standard store" configuration it works fine.
> 
> I do not know if I understand. @wanxe
> 
> You mean it's not working with namespace modules?

Exactly.

**Comment by xereda** [comment] 2019-02-05 12:15
@wanxe I created a project with namespaced modules. There were no problems.

**Comment by Akryum** [comment] 2019-02-05 12:24
If think he meant dynamically registered modules with `store.registerModule`.

**Comment by xereda** [comment] 2019-02-05 13:00
@Akryum @wanxe The modules I maintain are registered manually. But the application is a suite of modules. So, before my module, it has the store of the framework and it is registered dynamically.

**Comment by xereda** [comment] 2019-02-05 16:50
I made a repository available with the simulation. Just clone it and run the dev environment.

https://github.com/xereda/vue-devtools-5

**Comment by Sp1ker** [comment] 2019-02-05 19:04
It's not work in 4.1.5 too.
Its "work" only on <250ms `registerModule`. After 250ms modules will not shown in devtools too

For correct work `registerModule` must be like a mutations with history and revert or replay. Like a `Base State` item.

**Comment by xereda** [comment] 2019-02-06 11:33
@Sp1ker 

Thank you so much for the help. The issue is that I did not really understand why the same dynamic had its state presented in version 4.1.5 and not presented in version 5 beta 4. This without my intervention. It only always works in version 4, but not in version 5.

**Comment by xereda** [comment] 2019-02-06 11:38
@Sp1ker @Akryum 

In both simulations:
  - The same project;
  - The same states;
  - The same dynamic store and being created at the same point;
  - For both simulations, I did not make any changes;

Considering the facts above. I did not really understand the difference that causes the presentation in version 4.1.5, but it does not let you present in the new beta version (5 beta 4).

**Comment by Sp1ker** [comment] 2019-02-06 12:01
> Considering the facts above. I did not really understand the difference that causes the presentation in version 4.1.5, but it does not let you present in the new beta version (5 beta 4).
In your repo replace it:
```
this.$store.registerModule('dynamicVuexModule', dynamicVuexModule); 
```
with:
`setTimeout(() => {this.$store.registerModule('dynamicVuexModule', dynamicVuexModule)}, 500)`

It's not work on 4.1.5 too.

**Comment by xereda** [comment] 2019-02-06 12:20
>>> It's not work on 4.1.5 too.

**Comment by Sp1ker** [comment] 2019-02-06 12:39
>`registerModule` works fine in version 4. Even without applying debounce in the method.
for 4.1.5:

Without debounce your dynamic module will register before initializing vuex and importing state in devtools because vuex state importing after 250ms:
```
importState: debounce(function (e) {
      // ....
      }
}, 250)
```
It is work.
But if you add debounce in your example `registerModule` will be called after importing vuex state in devtools. It is not work.

Your repository is special case of that problem.
In any case it must be fixed in future versions by Akryum :)

P.S. Sorry for my english.

**Comment by xereda** [comment] 2019-02-06 12:44
@Sp1ker There are no problems with your English. Thanks for the engagement. I'll wait for a return from @Akryum.

**Comment by ffxsam** [comment] 2019-03-09 16:21
I'm having this issue too. I'm registering a module inside a Vue plugin, and while I can click a component and check my state via `$vm0.$store.state.myPlugin` and that works, I cannot use the Vue DevTools UI to look at the state.

![image](https://user-images.githubusercontent.com/12532733/54074184-0aa8d180-4255-11e9-9325-69200b18f508.png)

Also, in my mutation function, the `state` argument is `undefined`.

**Comment by laander** [comment] 2019-03-14 11:44
Same here, new beta throws the error @ffxsam posted when calling `store.registerModule` (inside a Vue plugin)

**Closed** 2019-03-21 01:58 UTC
Labels: bug, need team repro

**Comment by laander** [comment] 2019-03-21 07:28
@Akryum How come you closed the issue? Because you don't believe there's an issue or because a fix already has been implemented?

**Comment by przemkow** [comment] 2019-03-21 07:59
@laander there is a link to the commit which fix this issue. Next to the ticket status change.  
 https://github.com/vuejs/vue-devtools/commit/ba8b349063ccaf9598d778d977f907ffb385817b

**Comment by xereda** [comment] 2019-03-21 08:24
Is there any deadline for this to be released in an upcoming version of the extension?

**Comment by Sp1ker** [comment] 2019-03-21 09:57
5.0.0 beta 5 was released

**Comment by xereda** [comment] 2019-03-21 10:25
with This fix?

**Comment by laander** [comment] 2019-03-21 11:34
@przemkow Ah, of course. Head full of porridge, my apologies 🙈
