### ISSUE TITLE
Error on right click in Chrome 64

### ISSUE THREAD

**Issue by effectjared** [vuejs/vue-devtools#562] opened 2018-01-25 09:37 UTC
### Version
4.1.0

### Browser and OS info
Chrome 64 / MacOS 11.12.6

### Steps to reproduce
1. Right click anywhere in the window on any page, regardless of whether Vue is used on the page
2. Open console

### What is expected?
No errors to appear

### What is actually happening?
Getting a console error;

Uncaught ReferenceError: o is not defined
at HTMLDocument.document.addEventListener.t (<anonymous>:1:784)

---
It happens whether or not you have the console open at the time of right-clicking, and whether the Vue DevTools are active.

**Comment by Akryum** [comment] 2018-01-25 09:51
Duplicate of #514

**Closed by Akryum** 2018-01-25 09:51 UTC
