### ISSUE TITLE
Chrome Plugin Update

### ISSUE THREAD

**Issue by Erutan409** [vuejs/vue-devtools#600] opened 2018-01-30 20:28 UTC
### Version
4.1.2

### Browser and OS info
Chrome - Windows 10

### Steps to reproduce
Not completely sure, but it seems to occur when I navigate away from the Vue plugin within dev tools.

### What is expected?
Be able to click on components within root or root, itself and list component properties..

### What is actually happening?
When I hover over, I see new-looking component name button overlays in webpage.  But, I can't actually click/select said component to view the properties.  I have to close dev tools and re-open.

---
Can I rollback the update?

**Comment by Modelair** [comment] 2018-01-30 20:44
have this issues too.
it happens after webpack middle hot reload

**Comment by edwinencomienda** [comment] 2018-01-30 21:05
i have this problem too

Uncaught TypeError: Cannot redefine property: $isChrome
    at Function.defineProperties (<anonymous>)
    at e.a (devtools.js:1)
    at t.connect.t (devtools.js:1)
    at devtools.js:1
    at devtools.js:1
    at callbackWrapper (<anonymous>:60:1)
    at ExtensionServerClient._onCallback (<anonymous>:73:649)
    at ExtensionServerClient._onMessage (<anonymous>:74:9)
4devtools.js:1 Uncaught TypeError: Cannot read property '$el' of undefined
    at po.refresh (devtools.js:1)
    at o (devtools.js:1)
    at e (devtools.js:1)
    at HTMLAnchorElement.e._withTask.s._withTask (devtools.js:1)

**Comment by NonesuchStudios** [comment] 2018-01-30 21:23
Same problem! Chrome Version 63.0.3239.132 on MacOS High Sierra (10.13.2)

**Steps to reproduce:**
1. Load a tab with a running Vue app in it (http://todomvc.com/examples/vue/)
2. Open Chrome dev tools -> Vue
3. Reload tab

**What is expected?**
Vue dev tools will continue to function

**What is actually happening?**
Vue dev tools becomes entirely unresponsive (cannot select components or navigate bindings, cannot switch between componenets/vuex/events, cannot refresh) and stops reacting to changes on the page.

**Comment by pooot** [comment] 2018-01-30 21:43
Possible duplicate of https://github.com/vuejs/vue-devtools/issues/588#issuecomment-361585181

**Comment by Xationch** [comment] 2018-01-30 22:20
Same, how to rollback ?

**Comment by Akryum** [comment] 2018-01-30 23:42
Duplicate of #588

**Closed by Akryum** 2018-01-30 23:42 UTC
