### ISSUE TITLE
Devtools tries to serialize whole VNodes

### ISSUE THREAD

**Issue by jsm1003** [vuejs/vue-devtools#857] opened 2019-01-05 09:33 UTC
### Version
4.1.5

### Browser and OS info
Chrome 71.0.3578.98/Windows 10

### Steps to reproduce
git clone git@github.com:jsm1003/vue-devtools-bug.git

cd vue-devtools-bug

npm install

npm run serve

open chrome devtools

![bug](https://user-images.githubusercontent.com/19246339/50722826-04d92780-1110-11e9-9a90-d6ba8418ec65.gif)

### What is expected?
nothing happend

### What is actually happening?
memory leak caused by vue-devtools

**Comment by raphaelsoul** [comment] 2019-01-07 01:38
leak report by mocha.
![image](https://user-images.githubusercontent.com/8615787/50744638-e2eeba80-125f-11e9-8dd9-0856c1ec6668.png)

I'am using vue-devtools v4.1.5 beta on chrome

**Comment by peey** [comment] 2019-01-26 06:10
I've noticed a memory leak in Firefox as well. Browser Version 64.0 (64-bit) on Ubuntu 16.04, Vue Devtools version 4.1.5.

**Comment by dpiquet** [comment] 2019-02-19 14:28
Same here, firefox quantum 65, devtools 4.1.5.

I noticed that refreshing the page (ctrl+R) grows memory quite fast when app (spa) built in 'dev' mode. Closing the tab and opening a new one frees the memory.

If the app is in prod mode, devtool plugin is not started and memory usage is normal.

hope that helps to reproduce issue.

**Comment by Akryum** [comment] 2019-02-19 14:41
Could you try with the latest 5.0 beta?

**Comment by lamka02sk** [comment] 2019-02-20 20:41
Still an issue, one big nasty memory leak. I was wondering why my disk makes noise after a few hours of development and found out it was actually swapping. 10GB of RAM only Firefox :joy:

**Comment by luka-mikec** [comment] 2019-02-27 13:57
I'm not sure if this is related, but a serious leak (~100MB/sec) occurs when I select a component which has a proxied object whose length is (being reported through the proxy as) 10^15. I guess it has to do with JSON stringification somewhere. Perhaps stringifier should not try to stringify everything at once?

**Comment by peey** [comment] 2019-02-28 08:34
Status of this bug should be elevated. I have to use Devtools in a secondary browser so that my tabs on primary browser don't crash when I have to kill the process due to memory leak.

**Comment by Faymir** [comment] 2019-03-09 15:03
Same for me. huge memory leak when refreshing it goes from 1GB of ram  to 3Gb of ram used when refresh just 6 times.

**Comment by jcloutz** [comment] 2019-04-19 15:23
Same for me, firefox gets up to around 6GB of ram in less than an hour of working.

**Comment by LockonZero** [comment] 2019-05-10 07:36
Same here. I am working with a medium sized set of data and after refreshing a few times, Firefox is using ~5GB of RAM. Closing the tab and starting on a new one temporarily solves the problem

**Closed** 2019-06-26 23:00 UTC
