### ISSUE TITLE
__VUE_DEVTOOLS_UID__' of undefined

### ISSUE THREAD

**Issue by thisismyaim** [vuejs/vue-devtools#589] opened 2018-01-30 12:12 UTC
### Version
4.1.2

### Browser and OS info
mac os 10.13.3, Chrome Version 63.0.3239.132

### Steps to reproduce
In vue dev tools when i do inspect vue element it gives me error on click elements in left panel : 

Error is : 

```
Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_UID__' of undefined
```

more

```
e=>{h=e,function(e){const t=e.__VUE_DEVTOOLS_UID__
```

### What is expected?
don't know what is this.

### What is actually happening?
looks like i can't able to click, vue-dev tools hang

---
i can share video if require.

**Comment by samydoesit** [comment] 2018-01-30 12:30
We got the same error at [https://github.com/vuejs/vue-devtools/issues/588](url)

**Comment by Akryum** [comment] 2018-01-30 12:56
Duplicate of #588

**Closed by Akryum** 2018-01-30 12:56 UTC

**Comment by nathanchere** [comment] 2019-02-12 13:43
Be sure you aren't using the .min version of vue
It's not just minified, it is also missing dev tools
