### ISSUE TITLE
a version for safari will be available soon ?

### ISSUE THREAD

**Issue by stephanedemotte** [vuejs/vue-devtools#51] opened 2015-11-17 13:18 UTC
Safari is much faster than chrome, it could be great to have this extension :)

Thanks !

**Comment by amirrustam** [comment] 2016-01-14 22:10
I would also love to just use Safari, because it allows me to inspect apps running within iOS Safari, but from my quick search it doesn't look like there is an API to extend the Safari Web Inspector. Chrome has a very nice API for extending their inspector: https://developer.chrome.com/extensions/devtools

So I think Vue DevTools for Safari would just need to be an independent Safari extension and built like so: https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html

**Comment by yyx990803** [comment] 2016-01-14 22:28
The devtool's own code is browser-agnostic, it all talks through a standard events interface. However I've only got time to make the Chrome version. Theoretically you can build shells for FF/Safari as long as the extension runs as an HTML5 app. Feel free to contribute if anyone is interested.

**Comment by amirrustam** [comment] 2016-01-14 22:37
@yyx990803 I'm gonna work on this as soon as I get some extra time to dedicate to it. I've done some Safari extensions in the past. I'll report back here. 

Suggestions and tips are welcome in the mean time.

**Comment by yyx990803** [comment] 2016-01-14 22:40
I probably need to write some basic docs explaining the design and how things work, but the simplest way to start is looking at `shells/dev` which is basically a minimal shell example using an iframe.

**Comment by amirrustam** [comment] 2016-01-14 22:49
Some docs will be nice and helpful :+1: 

Once I figure out the Safari extension then I can easily do a Firefox version: https://developer.mozilla.org/en-US/docs/Tools/Adding_a_panel_to_the_toolbox

So then we can all live in peace and harmony on Earth. :)

**Comment by amirrustam** [comment] 2016-01-14 22:51
Spoke too soon, looks like someone has already got the FF version down #57

**Comment by mikebronner** [comment] 2016-04-20 14:01
@amirrustam have you made any progress on the Safari plugin? Would love that as well. :) I've run into the issue of Safari not allowing extending of the dev-pane as well. :(

**Comment by kartsims** [comment] 2016-06-21 14:46
@amirrustam Looking forward to peace and harmony on Earth ! (until then, Safari dev tools would also be nice)

**Comment by mesqueeb** [comment] 2016-07-23 16:54
I would love a Safari plugin! Because often my website works on Chrome, but not on Safari. It's really hard to find out what's exactly bugging in Safari!!! Any hints?

**Comment by amirrustam** [comment] 2016-07-29 20:27
@mikebronner @kartsims @mesqueeb wow, I got to get better at checking my Github notifications. Apologies for late response, but I've been deep in priority work, but working on the Safari Dev Tools plugin is on my to do list. FYI, I'm already running macOS Sierra Beta, so I will be testing it with that version of Safari.

**Comment by amirrustam** [comment] 2016-07-29 20:31
@mesqueeb can you possibly report the Safari errors or issues you are running into within a new issue, and we can continue the discussion there. If you think your problem is a bit too vague, then please start a thread within the forums.

**Comment by mesqueeb** [comment] 2016-07-29 23:16
@amirrustam I had a problem where safari and chrome would handle a click event on a checkbox different. But it's fixed now! My bad. : )
Anyway really looking forward to the dev toold on JS! Just being able to see the VUE JS object as a tree would be great help, so you could maybe have that as first version?

**Comment by dkleehammer** [comment] 2016-10-13 20:47
Would love a safari version as well!

**Comment by egoist** [comment] 2016-10-26 11:03
An even easier approach, deploy it as a Vue component so that user can use it via `<devtools></devtools>`. 😃

**Comment by mccjul** [comment] 2017-04-05 01:43
The problem is you have to pay 120 bucks to make it.

**Comment by xlcrr** [comment] 2017-04-16 13:33
Just noticed some problems in safari too, and even on chrome on iOS 

Some things not rendering and vm.$set(a, b, c); not working for me on either Safari or chrome iOS

**Comment by ruchern** [comment] 2017-05-18 17:47
@xlcrr Not unless you use Github and let the users build it themselves and install it. I mean whoever who needs to use Vue Dev tools I assume would also know how to follow the README and build them.

**Comment by iBobik** [comment] 2017-09-14 12:10
Is it possible to auto build extension in CI and upload it to GitHub releases? Same for Safari and Chrome.

**Comment by michalsnik** [comment] 2018-01-03 01:28
I see it's been resolved on June 14th. Can we close this PR @yyx990803  ?

**Comment by ruchern** [comment] 2018-01-03 03:13
@michalsnik Is there a way to workaround closing of Safari and resulting in the need to reinstall the extension?

**Comment by michalsnik** [comment] 2018-01-03 11:44
I'm not aware of any unfortunately @ruchern

**Comment by Akryum** [comment] 2018-01-03 11:45
[Follow the instructions to get it running in Safari](https://github.com/vuejs/vue-devtools/blob/master/docs/workaround-for-safari.md)

@michalsnik You can open another issue.

**Closed by Akryum** 2018-01-03 11:45 UTC
Labels: contribution welcome

**Comment by ruchern** [comment] 2018-01-03 14:57
@Akryum I know how to get it running, but you have to repeat the steps each time Safari is closed.
