### ISSUE TITLE
报错t.isBuffer is not a function

### ISSUE THREAD

**Issue by hellboy81** [vuejs/vue-devtools#898] opened 2019-03-08 15:51 UTC
### Version
5.0.0-beta.4

### Browser and OS info
Chromium 72.0.3626.109 / Windows 7

### Steps to reproduce
- Open browser with enabled vue-devtools
- Open page with vue and vuex store under control

### What is expected?
- Vue form with Vuex store should be shown

### What is actually happening?

- The empty page is shown
- The JS exception is thrown:

该问题是别人的浏览器正常，我的浏览器却报错，最终发现是chrome浏览器插件的原因。
我安装了一个 Vue.js devtools 插件出错，导致了该问题。

![image](https://user-images.githubusercontent.com/341600/54037911-8c4e2000-41bf-11e9-980a-9d85055eee85.png)

---
```js
VM6882:1 Uncaught TypeError: t.isBuffer is not a function
    at l (<anonymous>:1:1543)
    at i (<anonymous>:1:2395)
    at Object.n.once.t (<anonymous>:1:915)
    at Object.e (<anonymous>:1:369)
    at Object.emit (<anonymous>:1:688)
    at devtoolPlugin (vuex.esm.js:51)
    at new Store (vuex.esm.js:354)
    at Object.cbRa (index.js:13)
    at __webpack_require__ (bootstrap ac99b47fc4e390481f81:54)
    at webpackJsonpCallback (bootstrap ac99b47fc4e390481f81:25)
```

See also [issue](https://www.jianshu.com/p/34650688f06b)

**Comment by wiese** [comment] 2019-03-25 20:58
Possible duplicate of #874

**Comment by Akryum** [comment] 2019-03-25 21:03
Duplicate of #874

**Closed by Akryum** 2019-03-25 21:03 UTC
