### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by npelto** [vuejs/vue-devtools#826] opened 2018-11-16 11:36 UTC
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 70.0.3538.102 / Windows 10

### Steps to reproduce
Enable dev tools on a site that has lodash set to window._

### What is expected?
Site is expected to load normally

### What is actually happening?
I get the error: Uncaught ReferenceError: _ is not defined
And page fails to load.

**Comment by lwiml** [comment] 2018-11-19 16:53
same issue

**Comment by Sp1ker** [comment] 2018-11-21 08:52
Duplication of #825

**Comment by Akryum** [comment] 2019-01-24 18:15
Duplicate of #825

**Closed by Akryum** 2019-01-24 18:15 UTC
