### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xereda** [vuejs/vue-devtools#1078] opened 2019-10-04 12:36 UTC
### Version
5.1.1

### Browser and OS info
Chrome 76 / Arch Linux

### Steps to reproduce
Access an application with many stores.

### What is expected?
I want the performance to be better and not to crash the first time I open the extension.

### What is actually happening?
Vue dev tools breaks the first time I open the extension and performance is slow.

---
I did some animated gif simulations to help with debugging.

Setup:

![deepin-screen-recorder_Select area_20191004090852](https://user-images.githubusercontent.com/14337850/66206999-011b0700-e688-11e9-83da-bbe328035b06.gif)

What happens the first time?

![deepin-screen-recorder_google-chrome_20191004093832](https://user-images.githubusercontent.com/14337850/66208287-21989080-e68b-11e9-8a7f-3486b08f9b71.gif)

To solve this problem I refresh the browser. That way, the error no longer happens and I can have the state updated. It is still extremely slow, but it works.

![deepin-screen-recorder_google-chrome_20191004093345](https://user-images.githubusercontent.com/14337850/66207936-696ae800-e68a-11e9-95c9-6d6608623618.gif)

**Comment by xereda** [comment] 2019-10-04 12:49
One question: Why didn't we have these issues in the previous version of the extension? The performance was quite satisfactory, even in big stores.

**Comment by xereda** [comment] 2019-10-11 14:18
Did you leave the vue devtools?

**Comment by yyx990803** [comment] 2019-10-11 14:25
It's not about "leaving" - there are many things going on and we have priorities.

Ping @Akryum since he worked on the 5.0 release and should have the most context.

**Comment by mdartic** [comment] 2019-10-11 14:29
@xereda do you have your code available in a repo for testing purpose ?

**Comment by xereda** [comment] 2019-10-11 14:34
@yyx990803 I understand that. No problems. It was an excellent tool for the daily life of the programmer.

@mdartic I do not have the project in an open repository. Unfortunately. I can try to simulate in other ways.

**Comment by mdartic** [comment] 2019-10-11 14:38
I think it would be great, I encouter some problems too, but I can use it anyway.
You seem to encounter an error, so to reproduce it's better to have a codebase available ?

**Comment by Akryum** [comment] 2019-10-11 15:26
@xereda Would it be possible for you to give me access to your project privately via email?

**Comment by Akryum** [comment] 2019-10-11 15:28
Also, seems to be a duplicate of #997

**Comment by xereda** [comment] 2019-10-11 16:58
Hi @Akryum 

I can try to share the project of the module in question. The problem is that you will not be able to run the environment as it will depend on the backend to simulate. 
We don't have mock server.

**Comment by Akryum** [comment] 2019-10-11 17:07
Maybe we can do it with https://ngrok.com/

**Closed** 2019-10-30 17:55 UTC
