### ISSUE TITLE
PLS make an Edge extension and upload to edge shop, THX.

### ISSUE THREAD

**Issue by sasha6806** [vuejs/vue-devtools#1343] opened 2021-01-11 02:47 UTC
### What problem does this feature solve?
Users in china cannot visit chrome shop

### What does the proposed API look like?
same as vue-devtools chrome extension.

**Comment by westhom** [comment] 2021-01-17 14:09
Use the standalone Electron app: https://github.com/vuejs/vue-devtools/blob/dev/packages/shell-electron/README.md

**Comment by nikmanzotti** [comment] 2021-01-22 00:03
Seems to be a duplicate of https://github.com/vuejs/vue-devtools/issues/1155

**Closed** 2021-01-29 11:51 UTC
