### ISSUE TITLE
Since 5.0.0, breaks page with `isBuffer` is not a function.

### ISSUE THREAD

**Issue by jaketoolson** [vuejs/vue-devtools#910] opened 2019-03-25 20:08 UTC
### Version
5.0.0

### Browser and OS info
Version 73.0.3683.86 (Official Build) (64-bit)

### Steps to reproduce
Navigating my product's webpage (locally and in production) with vue tools, I get the following error:

```
 VM259:1 Uncaught TypeError: t.isBuffer is not a function
    at y (<anonymous>:1:2232)
    at f (<anonymous>:1:3275)
    at Object.<anonymous> (<anonymous>:1:928)
    at Object.r (<anonymous>:1:375)
    at Object.emit (<anonymous>:1:694)
    at t (vuex.min.js:6)
    at vuex.min.js:6
    at Array.forEach (<anonymous>)
    at new V (vuex.min.js:6)
    at Object.<anonymous> (app-74311e04b1.min.js:39)
```

Which points to the (minified) code: 
```if (g && t.isBuffer(e))``` 

### What is expected?
This shouldn't cause the web page I'm browsing to stop working.

### What is actually happening?
Web page I'm using with vue-devtools enabled in the browser stops working entirely.  If I disable the extension, the page/site loads just fine.

**Comment by Akryum** [comment] 2019-03-25 20:36
Duplicate of #874

**Closed by Akryum** 2019-03-25 20:36 UTC
