### ISSUE TITLE
Vue.js not detected

### ISSUE THREAD

**Issue by phlegx** [vuejs/vue-devtools#832] opened 2018-12-04 13:40 UTC
### Version
5.0.0-beta.3

### Browser and OS info
Firefox 63.0.3 (64-bit)

### Steps to reproduce
The add-on vue-devtools is not activated. It shows "Vue.js not detected".

I have created a Rails Vue app with a simple example. The app works fine. The only think the console shows is: "Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”)."
Can this error be the problem?

Vue.config.devtools is set to true. And I'm running in development mode.

On this website "https://new-issue.vuejs.org" the add-on works!

### What is expected?
vue-devtools should detect the Vue app.

### What is actually happening?
vue-devtools does not detect Vue.

**Comment by TheCycoONE** [comment] 2019-01-14 16:02
I think this is a duplicate of #616 (they changed from unsafe-inline to unsafe-eval)

**Comment by Akryum** [comment] 2019-01-24 18:13
Duplicate of #616

**Closed by Akryum** 2019-01-24 18:13 UTC
