### ISSUE TITLE
[Repro Provided] alert() triggers immediately on Base State

### ISSUE THREAD

**Issue by remixie** [vuejs/vue-devtools#1026] opened 2019-06-27 19:24 UTC
### Version
5.1.1

### Browser and OS info
Firefox 67.0.4 (64-bit) / Windows 10 Enterprise

### Steps to reproduce
1. Create a vue cli project that has a vuex store. 
2. Make a getters function inside of the vuex store.
2. Add an alert() to the inside of the getters function.
3. Run serve inside of vue ui.
4. Open app.
5. Open Developer Tools.
6. Go to the Vue Tab.
8. Once Base State loaded in, the alert() immediately runs.

### What is expected?
I expected that initializing Base State would not trigger the alert() inside of the getters function. 

### What is actually happening?
Base State triggers the alert() inside of the getters function. This behavior only occurs when Base State loads in so this is definitely a vue-devtools problem. When vue-devtools is disabled, the alert() stays untriggered.

---
I made a unit test of that demonstrates this issue: https://codesandbox.io/s/vue-devtools-alert-bug-44ewg

It seems that vue-devtools cannot hook up to the vue that's loaded into the preview window so please go to the preview url in a separate tab and THEN open vue-devtools. Note: It may take a couple of seconds for the page to load.

**Comment by Akryum** [comment] 2019-10-28 13:58
Duplicate of #443

Also side effects in getters is a very bad idea. 😸

**Closed by Akryum** 2019-10-28 13:58 UTC
