### ISSUE TITLE
Dev tools does not evaluate computed props that are not expressed in dom

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue-devtools#622] opened 2018-02-20 18:56 UTC
### Version
4.1.3

### Browser and OS info
Chrome, Win 10

### Steps to reproduce
During the development process, create a computed prop.  Do not yet consume that computed value in dom.  Dev-tools will fail to evaluate/update that prop, leading the user to believe there is an underlying reactivity issue.  This has resulted in a lot of unnecessary debugging/frustration/confusion.

### What is expected?
I expect to see the value continuously update, to mirror the behavior that I would have if I were to consume the prop.

I expect the dev-tools to consider itself as a dependency/evaluator of all computed props, or at least have the option to continuously evaluate computed props, so that users have a predictable experience.

### What is actually happening?
I have to refresh the dev-tools state tree or consume the prop in dom to see computed props continuously update.  Which is both confusing, and stifling to my development speed.

**Comment by posva** [comment] 2018-02-20 19:33
Duplicate of #393

**Closed by posva** 2018-02-20 19:33 UTC
