### ISSUE TITLE
tool error

### ISSUE THREAD

**Issue by svkala** [vuejs/vue-devtools#1333] opened 2020-12-29 10:34 UTC
### Version
6.0.0-beta.3

### Browser and OS info
Chrome, Win10

### Steps to reproduce
Start tool

### What is expected?
Not to generate an error

### What is actually happening?
We have an error when the tool tab has been clicked

---
Layout.vue?3e79:77 Unhandled rejection (promise:  Promise {<rejected>: TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at registerAppJob (chrome-extensi…} , reason:  TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at registerAppJob (backend.js:1414) ).
eval @ Layout.vue?3e79:77
backend.js:1414 Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at registerAppJob (backend.js:1414)
registerAppJob @ backend.js:1414
Promise.then (async)
run @ backend.js:4990
(anonymous) @ backend.js:4993
onDone @ backend.js:4984
Promise.then (async)
run @ backend.js:4990
(anonymous) @ backend.js:4996
queue @ backend.js:4979
waitForAppsRegistration @ backend.js:1459
connect @ backend.js:704
initBackend @ backend.js:675
async function (async)
initBackend @ backend.js:670
handshake @ backend.js:1605
postMessage (async)
o @ proxy.js:1
290 @ proxy.js:1
n @ proxy.js:1
(anonymous) @ proxy.js:1
(anonymous) @ proxy.js:1
Layout.vue?3e79:77 Unhandled rejection (promise:  Promise {<rejected>: TypeError: Cannot read property 'id' of null
    at getComponentInstance (chrome-extension://ljjeml…} , reason:  TypeError: Cannot read property 'id' of null
    at getComponentInstance (backend.js:3130)
    at Object.sendComponentTreeData (backend.js:3059)
    at Bridge.<anonymous> (backend.js:738)
    at Bridge.emit (backend.js:4484)
    at Bridge._emit (backend.js:1102)
    at backend.js:1034
    at Array.forEach (<anonymous>)
    at backend.js:1034
    at listener (backend.js:1581) ).
eval @ Layout.vue?3e79:77
backend.js:3130 Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at getComponentInstance (backend.js:3130)
    at Object.sendComponentTreeData (backend.js:3059)
    at Bridge.<anonymous> (backend.js:738)
    at Bridge.emit (backend.js:4484)
    at Bridge._emit (backend.js:1102)
    at backend.js:1034
    at Array.forEach (<anonymous>)
    at backend.js:1034
    at listener (backend.js:1581)
getComponentInstance @ backend.js:3130
sendComponentTreeData @ backend.js:3059
(anonymous) @ backend.js:738
emit @ backend.js:4484
_emit @ backend.js:1102
(anonymous) @ backend.js:1034
(anonymous) @ backend.js:1034
listener @ backend.js:1581
postMessage (async)
o @ proxy.js:1

**Comment by ygj6** [comment] 2021-01-13 03:43
@svkala Based on experience, I think you may use `6.0.0-beta.3` to debug your `vue2` project, or your chrome extension has both `6.0.0-beta.3` and `5.3.3` installed.

**Comment by boku-syokou** [comment] 2021-01-18 12:32
just uninstall vue extension 6.0.0-beta.3 form you chrome, then you can fix this issue

**Comment by Akryum** [comment] 2021-01-29 11:24
Duplicate of #1289

**Closed by Akryum** 2021-01-29 11:24 UTC
Labels: v6
