### ISSUE TITLE
Can you please provide a similar extension for firefox ?

### ISSUE THREAD

**Issue by neeravp** [vuejs/vue-devtools#57] opened 2015-11-28 05:32 UTC
Kudos!! The extension is a must while learning Vue atleast. I would like to request you to provide a similar extension for Firefox.

Please! can i expect it?

### Update: (17-March-2017)  
It is now possible to use (chrome's) vue dev-tools in Firefox.  
  
1. Install Firefox Developer Edition  
2. Install Chrome Store Foxified extension  
3. Now go to Chrome Web store and search for vue- devtools, you will now see an  **Add to Firefox** option   
4. Once you click on `Add to Firefox` you will get a pop up with different options, choose **Save Signed Addon** option and save the file to your disk.  
5. Now navigate to `about:addons` in Firefox and click on the ***gear*** icon in the top right corner (just before the search field), you will see an option **Install Addon from File** in the dropdown menu.  
6. Click `Install Addon from file` and choose the file which you downloaded and saved in **Step 4**.  
7. The `vue-devtools` will get installed in Firefox, restart Firefox and start using **vue-devtools** in Firefox.

**Comment by yyx990803** [comment] 2015-11-28 06:22
It's definitely planned in the future, however probably not until a few months out...

**Comment by neeravp** [comment] 2015-11-28 17:50
Thanks. Eagerly awaiting.

**Comment by skyronic** [comment] 2015-11-30 13:10
I've started work on a firefox version of the same. You can check out [my branch](https://github.com/skyronic/vue-devtools/tree/firefox) hope to finish this in 2-4 weeks. 

Progress so far:

![2015-11-30-173650_1920x1080_scrot](https://cloud.githubusercontent.com/assets/80173/11472287/7ad2dc2a-9791-11e5-93bc-c6d4408ce6bb.png)

**Comment by yyx990803** [comment] 2015-11-30 14:49
@skyronic very cool! Excited to have someone working on this. Let me know if you have any questions :)

**Comment by neeravp** [comment] 2015-11-30 18:34
Awesome  @skyronic , I will check out your branch.

**Comment by nacr-dev** [comment] 2016-05-09 13:49
@yyx990803 any news on this?

**Comment by PascalAOMS** [comment] 2016-05-29 17:12
Almost half a year later. :) Any news?

**Comment by neeravp** [comment] 2016-05-31 11:24
@yyx990803 , @skyronic  - any progress? still awaiting devtools for firefox

**Comment by ptibbetts** [comment] 2016-06-22 15:16
throwing in my vote as a firefox developer edition user

**Comment by j3j5** [comment] 2016-08-26 14:54
Is there any news on this? I'd love to be able to use FF dev edition for Vue just as I do with everything else. @skyronic? Any plans on finishing this or at least releasing some basic instructions to install what you already had?

Thanks!

**Comment by Jonas-buriti** [comment] 2016-11-16 16:17
Hey guys, are you still working in the FF version of dev tools? It would be a great enhancement... Tks!

**Comment by Drive4ik** [comment] 2016-11-17 16:37
Yes! I am still working on FF devtools, and I'll be happy with Vue plugin!! :)

**Comment by thewhitetulip** [comment] 2016-12-02 07:05
Hey folks, can we install a chrome plugin inside firefox? I remember reading this some time back. It was a blog post by Firefox team saying that we can easily install a chrome plugin inside firefox.

**Comment by adriaanzon** [comment] 2016-12-02 09:43
Yes, it's called WebExtensions. But I don't think it works developer tools.

see http://arewewebextensionsyet.com/#devtools.panels

**Comment by thewhitetulip** [comment] 2016-12-02 10:19
That's bad news.

**Comment by suncoastkid** [comment] 2016-12-12 19:17
Still no FF extension? :(

**Comment by ivansieder** [comment] 2016-12-16 12:20
@yyx990803 You got any update on this topic?

**Comment by gluons** [comment] 2016-12-16 13:37
I've subscribed this issue for Firefox addon. 🔔
Firefox user life isn't easy with Vue as Chrome. 😭
Still looking forward to using Firefox addon. 😳

**Comment by imuller** [comment] 2016-12-22 16:47
My christmas wish this year: that there will be a Firefox version of vue-devtools 🎄

**Comment by Draluy** [comment] 2017-01-08 23:18
I'm interested in this too.

**Comment by thewhitetulip** [comment] 2017-01-09 03:21
Anyone here wishes to build a firefox addon for Vue? I am open to collaborating, we can build our own version by checking the source code of the chrome version, do let me know if anyone is willing to participate.

**Comment by Draluy** [comment] 2017-01-09 18:29
Skyronic has started working on it it would seem, maybe try to get in touch?
As for me, my plate is full atm unfortunately.

**Comment by skyronic** [comment] 2017-01-09 19:10
Hey I had gotten some work done on this a long time ago by re-using ideas from the react-devtools project. I stopped using firefox due to some other reason so I didn't continue work on this. 

A lot of the structure for vue-devtools is inspired by https://github.com/facebook/react-devtools

so you'd want to create a folder in 'shells' similar to this one - https://github.com/facebook/react-devtools/tree/master/shells/firefox

**Comment by thewhitetulip** [comment] 2017-01-10 01:04
The maybe I can start working on your version itself. I've never written a extension, so it will take a little time!

**Comment by samrayleung** [comment] 2017-01-23 13:29
look forward to the firefox version

**Comment by wamoyo** [comment] 2017-02-01 03:00
So, which features are prevent this from just being ported over? 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

**Comment by wamoyo** [comment] 2017-02-01 03:03
I can confirm that this doesn't work for our case: https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by brunjick** [comment] 2017-02-07 17:38
@wamoyo devtools.panels API is needed http://arewewebextensionsyet.com/#devtools.panels
[Some progress has been made](https://reviewboard.mozilla.org/r/76818/diff/13) recently, so hopefully we will be able to port easily soon

**Comment by locolauty97** [comment] 2017-02-07 22:40
This is a so-needed tool 👎 I don't want to use chrome for this matter either

**Comment by stefanpolzer** [comment] 2017-02-17 21:14
Why is there still no plugin for Firefox? Would really appreciate it!

**Comment by posva** [comment] 2017-02-17 21:26
Because Vue + core libs  is more prioritised than this

**Comment by miladjef** [comment] 2017-02-26 07:01
My year wish this develop this add-ons for firefox .

**Comment by dobromir-hristov** [comment] 2017-03-15 07:29
Just to let you know, firefox Developer edition now has the panel displayed. It doesnt work atm, doesnt recognize the Vue app, but its showing up! We are almost there 😆

**Comment by thewhitetulip** [comment] 2017-03-15 08:59
@dobromir-hristov How do I install this for Firefox Dev edition?

**Comment by gluons** [comment] 2017-03-15 09:19
@thewhitetulip Go to `about:debugging#addons` and click button and browse to add-on file (`manifest.json`).

**Comment by dobromir-hristov** [comment] 2017-03-15 09:37
There is a plugin in firefox plugins to install Chrome Extensions directly from the Chrome Extensions website.

**Comment by thewhitetulip** [comment] 2017-03-15 11:51
@gluons @dobromir-hristov I'll try this today and let you know, thanks!

**Comment by gluons** [comment] 2017-03-15 13:27
We should wait until Mozilla finish dev tool API.

[![chrome incompatibilities mozilla mdn](https://cloud.githubusercontent.com/assets/4688092/23950450/9ae7eff6-09bd-11e7-8d44-e10764bacba7.png)](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Planned_APIs)

**Comment by wamoyo** [comment] 2017-03-15 18:57
@gluons That's probably only a few months out then, no?

**Comment by brunjick** [comment] 2017-03-15 19:31
it does work already on Aurora channel with Chrome Store Foxified extension
![screenshot at mar 15 23-30-07](https://cloud.githubusercontent.com/assets/6980903/23967202/6c7e1248-09d7-11e7-80a9-71c805ec6993.png)

**Comment by thewhitetulip** [comment] 2017-03-16 04:28
@brunjick Thanks for the update! I have the Aurora channel installed, will try and confirm back!

**Comment by Zetaphor** [comment] 2017-03-16 22:47
Also confirmed working with the latest release of dev edition and vue devtools.

* Firefox Dev Edition aurora 54.0a2 (2017-03-15) (64-bit)
* Chrome Store Foxified 2.4
* Vue.js devtools 3.1.2

**Comment by thewhitetulip** [comment] 2017-03-17 04:14
@neeravp  Can you please update the content of this issue to state that the extension now works with Firefox?

**Comment by neeravp** [comment] 2017-03-17 06:30
@thewhitetulip I have updated the issue content .

**Comment by thewhitetulip** [comment] 2017-03-17 08:46
@neeravp Thank you!

**Comment by Jonas-buriti** [comment] 2017-03-17 16:21
@brunjick tks! Here is working too att Firefox Dev Edition with Chrome Store Foxified.
Look it @mauricionr

**Comment by Hendriksie** [comment] 2017-03-20 09:09
Tested it on the latest release of Firefox (**52.01 (64-bit)**), although I get the icon next to me addressbar, no Vue pane can be found.

![](https://puu.sh/uRgS7.png)

![](https://puu.sh/uRgYq.png)

**Comment by brunjick** [comment] 2017-03-20 09:11
@Hendriksie Latest release is [54.0a2 (2017-03-19) (64-bit)](https://www.mozilla.org/en-US/firefox/54.0a2/releasenotes/)

**Comment by Hendriksie** [comment] 2017-03-20 09:14
@brunjick forgot to mention that I use the normal release version, no dev edition / aurora edition

**Comment by dobromir-hristov** [comment] 2017-03-20 09:23
@Hendriksie Yes, we are using the dev edition :)

**Comment by thewhitetulip** [comment] 2017-03-20 09:24
Anyone here would like to write a guide about how to install this addon? I wasn't able to install it!

**Comment by gluons** [comment] 2017-03-20 09:25
@thewhitetulip They use [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/).

**Comment by thewhitetulip** [comment] 2017-03-20 09:28
@gluons I did use that addon, it asked me to sign in using Firefox dev account, I did that, but I didn't get an option to install the addon, I could just download the .crx version or temporarily install it, I'll take a look at it today and let you know.

**Comment by neeravp** [comment] 2017-03-20 10:04
@thewhitetulip If you have downloaded the addon, then you can go to the addon management interface in firefox by navigating to `about:addons`.   
 
Once on the `about:addons` interface, you can click the `gear` icon in the top right before the search field and you will get an option `Install Add-on from file`, it will allow you to install the downloaded addon.    

Hope this helps.

**Comment by thewhitetulip** [comment] 2017-03-20 15:19
@neeravp This is awesome, thank you! I was able to install the addon and it looks cool. Thank you very much.

**Comment by Zetaphor** [comment] 2017-03-20 15:36
@thewhitetulip @neeravp It should be mentioned for any future Googlers, you first want to choose the "Save Signed Addon" option. This will generate a signed XPI file you can then install from the about:addons page.

**Comment by thewhitetulip** [comment] 2017-03-20 15:59
@neeravp @Zetaphor is right, it would be amazing if you could just copy paste the message which you sent me, the exact steps to install the addon at the top of the issue in the description, so new people finding this page via google won't face any issues.

**Comment by neeravp** [comment] 2017-03-20 17:27
@yyx990803 Should I close the issue Evan? Or should it be open till a native Firefox addon/extension is available?

**Comment by gluons** [comment] 2017-03-20 23:39
I think it should be opened til devtools API released.

This issue is for Firefox add-on. Not for installing Chrome extension in Firefox.

**Comment by thewhitetulip** [comment] 2017-03-21 01:31
@gluons Yes, until this is available in normal Firefox we should wait, when it is however, we do not need a new addon in firefox thus, we can close this, what do you think?

**Comment by yyx990803** [comment] 2017-03-21 02:07
Well, that is good news, but I think I will keep this open until the required features land in Firefox stable. In the meanwhile, I'd be happy to take a PR updating the README to point out how to use this extension in Firefox dev build.

**Comment by neeravp** [comment] 2017-03-21 04:42
I was thinking about a PR, but there are two things holding me back. First I have never contributed to any open source project by means of PR so am not sure about how to do it properly. I can prepare a gist and send it across you @yyx990803 .    

But even before that using Chrome Store Foxified requires to sign the extension/addon, for which I had to create an account at AMO. What I am wondering is that for anyone who wants to use vue-devtools in Firefox will need to open an account at AMO just for the purpose of signing the extension.  

Wouldn't it be better if we (anyone) can create an accont at AMO and sign the extension and then download the signed extension, which can then be included in this repo as a workaround for Firefox.  
  
Then any subsequent users can just download the signed extension from here and use `Install Addon from file` to get vue-devtools working in firefox.    

I am trying to figure out if such a signed extension can be reused.

**Comment by thewhitetulip** [comment] 2017-03-21 04:47
@neeravp There is no rocket science in submitting a PR, you just fork the project, edit the README.md file and submit it as a PR, based on the time @yyx990803 or other collaborators have, they'll merge it.

I agree with you and I was going to say this earlier, we can just upload a signed version of the addon rather than have everyone create a firefox account as it is a waste of time and resources, if you are willing, I'd send my addon to you, just try to install it on your firefox dev, and if that's fine, we can upload it directly on github itself.

**Comment by andreicristianpetcu** [comment] 2017-03-24 20:56
If you are fine with an unofficial build and want to run VueJS DevTools without the hassle of singing and converting the addon, I made one [here](https://andreicristianpetcu.github.io/chrome2firefox/).

I posted a lot of info related to Firefox addons on [this issue](https://github.com/vuejs/vue-devtools/pull/296#issuecomment-289137078) in case you need the info.

**Comment by soapdog** [comment] 2017-04-09 00:51
I just picked the built version in ```shells/chrome```, duplicated that into ```shells/firefox``` and used the [web-ext tool](https://www.npmjs.com/package/web-ext) and packed it. It is working for me. It would be trivial to ship that to AMO. It would be cool if the original author did it.

**Comment by dobromir-hristov** [comment] 2017-04-10 09:15
Do you guys have problems with the Vue devtools panel not being scrollable? Because I have to close all the tree branches to be able to see anything that is in the lower part of the panels, for example in the Vuex Store panel.

**Comment by zironycho** [comment] 2017-04-25 00:14
I am using Waterfox. I installed vuejs devtool, and restarted browser. However I couldn't find Vue tab in inspect window.

**Comment by clarkbw** [comment] 2017-05-30 20:37
We're still waiting on Firefox to complete [bug 1300590](https://bugzilla.mozilla.org/show_bug.cgi?id=1300590) such that `$0` and `inspect` bindings will work in the `devtools.inspectedWindow.eval` API.  Once that lands this is the list of things I believe need to be done for this issue to be closed out.  

- [ ] #339 : update the [manifest.json permissions](https://github.com/vuejs/vue-devtools/blob/master/shells/chrome/manifest.json#L35)
- [ ] Change [enabled popup text](https://github.com/vuejs/vue-devtools/blob/master/shells/chrome/popups/enabled.html#L3) to say "Open DevTools"
- [ ] Need to review the [webpack options for target browser](https://github.com/vuejs/vue-devtools/blob/b921b78b5117e86d495cb2a71a30777c6cd641e0/shells/chrome/webpack.config.js#L6) and [dev mode](https://github.com/vuejs/vue-devtools/blob/702f0149d5ed2b5a3a98de4c74f1fa011b2489b0/shells/dev/webpack.config.js#L7) I think we could likely just add `{ firefox: 55 }`
- [ ] Update [manifest description](https://github.com/vuejs/vue-devtools/blob/c32a92d27f3f8a5c2498f9a97484fa81db87e178/shells/chrome/manifest.json#L4) to mention Firefox as well as Chrome
- [ ] Investigate [custom fonts](https://github.com/vuejs/vue-devtools/blob/702f0149d5ed2b5a3a98de4c74f1fa011b2489b0/src/devtools/global.styl#L4-L14) that aren't working in Firefox
- [ ] Submit WebExtension zip to [AMO](https://addons.mozilla.org/)
- [ ] Update [README](https://github.com/vuejs/vue-devtools/blame/3ad08d2072eb03cf226026575b61d62bc4cc56e4/README.md#L17) to refer to Firefox extension
- [ ] Remove [Firefox workaround doc](https://github.com/vuejs/vue-devtools/blob/4a50a8afe8bd43b305acb65f4d809fd8c82f03bb/docs/workaround-for-firefox.md)

**Comment by clarkbw** [comment] 2017-05-30 20:44
> Investigate custom fonts that aren't working in Firefox

I'm getting this error:

```
downloadable font: GSUB: too large substitute
```

And it looks like this stackoverflow answer might be the path forward: https://stackoverflow.com/a/36803177/897414

**Comment by clarkbw** [comment] 2017-06-01 13:10
> Need to review the webpack options for target browser and dev mode I think we could likely just add { firefox: 55 }

Getting an error with 55 right now. Chrome is currently shipping 58 and 60 for Canary so I don't think it'll be an issue to use Fx 48 for now.

Here's the error:

```
Module build failed: Error: Support data exists for the following versions of firefox: 43, 44, 45, 46, 47, 48. Please raise an issue at https://gitlab.com/Rich-Harris/buble/issue
```

**Comment by andreicristianpetcu** [comment] 2017-06-04 18:20
[Bug 1300590 - Implement support for $0 and inspect bindings in devtools.inspectedWindow.eval](https://bugzilla.mozilla.org/show_bug.cgi?id=1300590) just landed. It will probably be available in the next Nightly update :D

**Comment by LaiHuanMin** [comment] 2017-06-09 03:44
Great! Hope this plan come true soon

**Comment by lionel-bijaoui** [comment] 2017-06-16 08:47
This is now [official](https://hacks.mozilla.org/2017/06/firefox-54-e10s-webextension-apis-css-clip-path/), but how exactly I install it on Firefox ?
Do I still need this [workaround](https://github.com/vuejs/vue-devtools/blob/master/docs/workaround-for-firefox.md) ?
I someone working on an official Firefox addon ?
This is very exciting!

**Comment by gluons** [comment] 2017-06-16 08:53
@lionel-bijaoui 
> Firefox continues its rapid implementation of new WebExtension APIs. These APIs are designed to work cross-browser, and will be the only APIs available to add-ons when **Firefox 57** launches this November.

It's on Firefox 57? It may not work now. I think still need it for now.

**Comment by lionel-bijaoui** [comment] 2017-06-16 09:00
@gluons Oh... I read it to fast it seem... I will wait then... 😞

**Comment by gluons** [comment] 2017-06-16 09:05
@lionel-bijaoui [**Firefox Nightly**](https://www.mozilla.org/en-US/firefox/nightly/all/) is 56 now. So close. Let's try it when 57 come. 😜

**Comment by andreicristianpetcu** [comment] 2017-06-16 12:21
@lionel-bijaoui having a workaround is silly when you can have a [one click install](https://andreicristianpetcu.github.io/chrome2firefox/addons/unofficial_vuejs_devtools-3.1.2-an+fx.xpi) I really hope the VueJS DevTools devs spent a few minutes to provide an official unlisted addon untill it will be ready to be listed on [AMO](https://addons.mozilla.org). It makes no sense to wait for v57 especially since some of us use v56 already.

**Comment by Hendriksie** [comment] 2017-06-16 13:06
Installing Vue-devtools via the workaround (https://github.com/vuejs/vue-devtools/blob/master/docs/workaround-for-firefox.md) works great on Firefox 54 (released just a few days ago).

Only thing I noticed is that I can't scroll inside the devtools window.

**Comment by lionel-bijaoui** [comment] 2017-06-16 13:18
@andreicristianpetcu THANK YOU! It work perfectly (except for the scroll)

**Comment by andreicristianpetcu** [comment] 2017-06-16 14:57
@Hendriksie what is the advantage of the workaround over the [one click install I proposed](https://andreicristianpetcu.github.io/chrome2firefox/addons/unofficial_vuejs_devtools-3.1.2-an+fx.xpi)? The workaround seems complicated and unnecessary but please correct me if I'm wrong. I tend to like thing that just work.

**Comment by callahad** [comment] 2017-06-16 15:22
Either is fine. Using Chrome Store Foxified directly just cuts out a middleman :)

Based on @clarkbw's [comment above](https://github.com/vuejs/vue-devtools/issues/57#issuecomment-305000683), it looks like all the pieces are in place for this, we just need to get it submitted to AMO and wait for the next release of Firefox to pick up a few fixes on our end.

**Comment by gluons** [comment] 2017-06-20 06:17
[**Something appeared in AMO**](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/) :ghost:

**Comment by clarkbw** [comment] 2017-06-20 14:30
Firefox workaround doc was removed in c8b9b1e5428fe6c834619d21f00e1e7c620deeb4 and README was updated in 182fe6875f2b2d9b2479f6b4bee1a52863b77f37

I think we're all done here!  

Thanks to everyone who helped and especially @yyx990803

**Closed** 2017-06-20 14:31 UTC

**Comment by gluons** [comment] 2017-08-11 16:01
@yyx990803 Can you add Vue logo on AMO page? Maybe easier to recognize.
