### ISSUE TITLE
Any way to run dev-tools on an app/extension?

### ISSUE THREAD

**Issue by jofranmi** [vuejs/vue-devtools#130] opened 2016-08-04 06:45 UTC
Hello, I'm working on a Chrome app, I got Vue up running on it but I can't seem to get the devtools in the console app, any way around this?

**Comment by posva** [comment] 2017-01-17 08:28
Sorry for the delay.
Did you find a way of doing it?

**Comment by SoullessWaffle** [comment] 2017-01-29 12:13
@posva I can confirm that Vue dev tools does not detect Vue instances injected into the page by Chrome extensions.

I've created a fairly minimal issue reproduction repo here: https://github.com/SoullessWaffle/yaglman/tree/devtools-repro

### Issue reproduction steps

1. `$ git clone https://github.com/SoullessWaffle/yaglman.git`
2. `$ git checkout devtools-repro`
3. `$ npm install`
4. `$ npm run watch`
5. Open Chrome and go to Extensions, ensure `Developer mode` is checked in the top right
6. Click `Load unpacked extension` and select the project's `dist` directory
7. Navigate to any GitHub labels page, e.g. https://github.com/vuejs/vue/labels
8. Open the Chrome dev tools
9. Observe that the Vue tab is not shown, the Vue dev tools icon on the top right
   of the browser window is greyed out and when clicked says "Vue.js is not detected"
   despite there being a Vue instance on the page  (the import/export buttons on the labels table)

### Expected behavior

The Vue instance is detected and the Vue tab shows up in the Chrome dev tools

**Comment by posva** [comment] 2017-01-29 12:50
Maybe we could learn from redux or react devtools. I think they support this. https://github.com/zalmoxisus/redux-devtools-extension/blob/v2.2.1/src/browser/extension/inject/index.js

**Comment by posva** [comment] 2017-02-15 12:18
Closing in favour of #120

**Closed by posva** 2017-02-15 12:18 UTC
Labels: feature request

**Comment by SoullessWaffle** [comment] 2017-02-15 19:27
@posva Would adding `chrome-extension://*` [here](https://github.com/vuejs/vue-devtools/blob/aa1c1583fc38493a39f8fedcc01f1e0ab7d2a757/shells/chrome/manifest.json#L32-L36) work? It wouldn't fix the detection issues for content scripts I described above but perhaps it might allow the devtools to work in chrome apps.

**Comment by posva** [comment] 2017-02-15 20:48
It doesn't seem to be a valid one :(

**Comment by SoullessWaffle** [comment] 2017-02-15 21:21
Damn :/
Maybe `chrome-extension://*/*`? Probably not but worth a try.

If it's not valid then maybe it's a Chrome security thing where it doesn't let extensions modify other extension pages...

**Comment by posva** [comment] 2017-02-15 21:25
nope 😞

**Comment by yesm1994** [comment] 2019-05-06 09:58
@jofranmi Same issue here! Did you find any solutions?
I'm using Vue.js to develop chrome app, I can use https://github.com/jusio/storage-area-explorer correctly in chrome apps.，but after reading vue-devtools's source code，
This project just not support chrome app to develop.
Due to Chrome APP security reasons, injectScripts(), remote Shell are both forbidden.
Can't find a proper way to use devtools, which makes me freak out.

I really hope Vue devtools can be used every where.

**Comment by Akryum** [comment] 2019-05-06 10:01
There is a standalone devtools app as listed in the README: https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md

**Comment by yesm1994** [comment] 2019-05-06 10:08
@Akryum Unfortunately, I've tried this solution, Chrome‘s CSP in Chrome app not allow to load script like this also.

**Comment by yesm1994** [comment] 2019-05-27 05:59
Any one who is looking for a solution to use this devtools,  modifying source code is needed.
