### ISSUE TITLE
Support Firefox (as it supports Chrome extensions now)

### ISSUE THREAD

**Issue by dobromir-hristov** [vuejs/vue-devtools#208] opened 2016-12-23 08:35 UTC
I just had to ask. Yesterday I installed the devtools into Firefox Developer Edition and seemed to work. The Vue Logo light up when I opened my project, but you cant really access the Vue tools as they are in the Chrome inspect tools. Is it possible, to make them appear in the firefox dev tools somehow?
I really hope its just a matter of checking where to attach the Vue Devtools window and the rest works as in Chrome.

**Comment by adriaanzon** [comment] 2016-12-24 14:31
See https://github.com/vuejs/vue-devtools/issues/57#issuecomment-264413939

It should work out of the box as soon as the WebExtensions API adds support for panels. Until then, I don't think it would be as easy. Or maybe someone can have a look at how react devtools [implements](https://github.com/facebook/react-devtools/tree/master/shells) this...

**Comment by posva** [comment] 2017-01-17 08:46
duplicate of #57

**Closed by posva** 2017-01-17 08:46 UTC
