### ISSUE TITLE
Component tree not supported

### ISSUE THREAD

**Issue by Br4x** [vuejs/vue-devtools#1237] opened 2020-07-21 09:28 UTC
### Version
6.0.0-beta.1

### Browser and OS info
Chrome 84 / Windows 10

### Steps to reproduce
Have a nuxt project

### What is expected?
Devtools working correctly

### What is actually happening?
An error appears "Component tree not supported" and devtools is unusable

---
Is there a way to downgrade vuedevtools?

**Comment by mtorromeo** [comment] 2020-07-21 09:30
Duplicate of #1235

**Closed** 2020-07-21 09:39 UTC
