### ISSUE TITLE
Duplicate Component Trees

### ISSUE THREAD

**Issue by monooso** [vuejs/vue-devtools#645] opened 2018-03-12 13:25 UTC
### Version
4.1.4

### Browser and OS info
Chrome 65.0.3325.146 / macOS 10.13.3

### Steps to reproduce
Open the `vue-devtools` extension, and navigate to the "Components" tab. You should see several identical Components trees (three, in my experience). For example:

```
<Root>
  <MyApp>
<Root>
  <MyApp>
<Root>
  <MyApp>
```

### What is expected?
`vue-devtools` should display a single Component tree, as per previous version of the extension.

### What is actually happening?
`vue-devtools` displays several duplicate Component trees.

---
This bug also appears on Chrome 64.x, and Firefox 58.x. It appears to have been introduced in `vue-devtools` version 4.1.4.

**Comment by aguingand** [comment] 2018-03-12 16:42
I have the same issue. As for me, it's happening when several of my components "`import Vue from 'vue'`"

**Comment by joelbradbury** [comment] 2018-03-13 09:34
I've got the same behaviour, introduced only in 4.1.4. The 4.1.3 devtools showed just a single component (as expected).

Interacting with any one of the component trees in the component view mirrors that action across all duplicated copies. (ie. expanding a collapsed node in copy 1, expands the same node in all other copies at the same time).

**Comment by monooso** [comment] 2018-03-13 09:42
One other thing to note. Interactions are mirrored, as described by @joelbradbury, _however_ (and it's an important however) setting a property value in one of the component trees doesn't necessarily set it in all of the component trees.

That's a real problem, and it's bitten me a couple of times already.

**Comment by lusess123** [comment] 2018-03-15 14:50
Duplicate removal rootInstances #647

**Comment by mirari** [comment] 2018-03-20 10:03
I've got the same behaviour.
![snipaste20180320_175752](https://user-images.githubusercontent.com/4995159/37647912-7d78e49c-2c68-11e8-9834-75855f65d442.png)
But my old project seems well.
I tried to copy `package.json`, `yarn.lock`, and all webpack configs, but still got the bug.
![snipaste20180320_175900](https://user-images.githubusercontent.com/4995159/37647916-7ed7be94-2c68-11e8-8257-7f1dd44b2b17.png)

**Comment by ericcirone** [comment] 2018-03-20 16:12
I'm having the same issue of multiple <Root> and components.

**Comment by badpunman** [comment] 2018-03-22 11:30
Same issues.

Also experiencing instability in some scenarios when trying to use the component name search. It just freezes the whole vue-devtools and requires a restart of the whole browser. Might be unrelated issue though, and worth separate item?

**Comment by rawbin-** [comment] 2018-03-22 12:20
![image](https://user-images.githubusercontent.com/8169783/37770169-7384008c-2e0e-11e8-986a-b27e113fb04c.png)

same issue

**Comment by caseyprovost** [comment] 2018-04-03 15:28
Im seeing this issue too

**Comment by vincentotsai** [comment] 2018-04-16 06:55
Same here.vue-devtools version at 4.1.4.
Everything seemed fine until I pressed the refresh btn,then I got Duplicate Component Trees.

![image](https://user-images.githubusercontent.com/23097939/38793931-c4d2194e-4185-11e8-956a-46f8f7ab08be.png)

**Comment by adriancast** [comment] 2018-04-23 13:31
I am having the same issue. I am using Vue 2.5.16 and the lasted version of the chrome extension.

**Comment by majorcool** [comment] 2018-05-08 04:04
What's going on for this issue?

**Comment by adriancast** [comment] 2018-05-08 05:15
I am still having the same issue :(

**Comment by netstuff** [comment] 2018-05-08 10:03
#metoo :)

**Comment by JH46666** [comment] 2018-05-15 03:42
Still exist

**Comment by justinkames** [comment] 2018-05-15 09:15
Having the same issue!

**Comment by KristofferBerg** [comment] 2018-05-15 11:58
Same issue here.

**Comment by ericcirone** [comment] 2018-05-15 15:16
Any update on timeline for fixing this?

**Comment by diazemiliano** [comment] 2018-05-15 20:31
Mee too.

**Comment by caryxiao** [comment] 2018-05-16 07:31
Mee too.... 
I almost thought there was a problem with my code, but too many people had the same problem. It didn't seem to be my code.

**Comment by C1NEMA** [comment] 2018-05-16 10:44
Any update on this? Is there a fix available yet just waiting to be merged or something?

**Comment by C1NEMA** [comment] 2018-05-16 12:31
Because of this issue, I was using the Electron based DevTools for a while now. I opened the DevTools within Chrome for the first time again and the bug went away?! I dont get it

![image](https://user-images.githubusercontent.com/16503129/40116947-ac9eb254-5915-11e8-86b2-5be79411b781.png)
( I got 2 seperate Vue instances so this is correct )

**Comment by adnanshussain** [comment] 2018-05-22 07:30
Same issue but it not happening with all Vue apps I make, only some of them :|

**Comment by mcparadip** [comment] 2018-05-26 23:50
Same issue here. Happened after I added a md-menu from vue-material.

**Comment by jsantoru** [comment] 2018-05-29 17:17
same issue here. i am also using `vue-material`

**Comment by whuper** [comment] 2018-05-31 02:09
I am using vue-material,and  I got same issue too...

**Comment by mswaidan** [comment] 2018-05-31 18:28
This also happens when I use vue-material

**Comment by rachardking** [comment] 2018-06-05 02:11
me too

**Comment by Deg5112** [comment] 2018-06-08 01:49
hey all, I've just re-installed the vue devtools extension, and the problem with duplicate component trees went away. Can we confirm this is the correct fix, does this work for anyone else?

**Comment by Linzdigr** [comment] 2018-06-15 12:43
[4.1.4] Same issue here with SSR and vue-material, nearly impossible to use, too much root nodes to be usable. 
What about this thread?

**Comment by cycold** [comment] 2018-06-15 13:17
Me too!

**Comment by ArStah** [comment] 2018-06-15 13:49
Same here, there are different amount of roots on different pages

**Comment by Cookizza** [comment] 2018-06-22 13:01
I've got this also, I only import Vue in one location.

**Comment by Linzdigr** [comment] 2018-07-01 18:03
On my side I use `router.beforeResolve` to call asyncData hook declared in navigable components for Server Side Rendering (as in https://ssr.vuejs.org/guide/data.html#client-data-fetching). The number of duplicated root elements depends on route component called.
Any idea on what's going on?

**Comment by sunchenguang** [comment] 2018-07-05 13:54
same issue for long days

**Comment by b4dnewz** [comment] 2018-07-11 06:43
hi, @majorcool how did you find out that was the cause? I'm curious to understand what cause this duplication problem

**Comment by DavidLambauer** [comment] 2018-07-19 19:51
same here :( Any Updates?

**Comment by fernyherrera** [comment] 2018-07-19 20:17
I get the same issue. It only happens to me when I am using dynamic components.

**Comment by Mmzer** [comment] 2018-07-25 08:53
Me too!

**Comment by ericcirone** [comment] 2018-07-25 17:00
WOOHOO! Can't wait for this to finally be pushed out. Thanks @Akryum

**Comment by ArStah** [comment] 2018-07-25 17:11
Eeeeeeah man!! Finally!! When the new version will be released?

**Comment by Akryum** [comment] 2018-07-25 17:49
Could someone try the master branch to see if the issue is resolved for you?

**Comment by ericcirone** [comment] 2018-07-26 14:00
@Akryum I cloned, npm install, npm run build. Load unpacked from shells/chrome. The problem is still there.
![image 2018-07-26 09-58-02](https://user-images.githubusercontent.com/10419347/43266971-add1830e-90ba-11e8-9795-9efafc04c23d.png)

**Comment by Akryum** [comment] 2018-07-26 14:08
@ericcirone Do you have a reproduction repository for me to check?

**Comment by ericcirone** [comment] 2018-07-26 14:34
@Akryum So i was messing around with the code and I fixed the issue, at least in my instance. I was looking back at 4.1.3 source since that works fine and was looking at the differences in the scan() function. 

So all i changed was not setting `instance` to be `instance.$root`

This is the scan function i am using now, and it is working as intended.

```javascript
function scan () {
  rootInstances.length = 0
  let inFragment = false
  let currentFragment = null
  walk(document, function (node) {
    if (inFragment) {
      if (node === currentFragment._fragmentEnd) {
        inFragment = false
        currentFragment = null
      }
      return true
    }
    const instance = node.__vue__
    if (instance) {
      if (instance._isFragment) {
        inFragment = true
        currentFragment = instance
      }

      // respect Vue.config.devtools option
      let baseVue = instance.constructor
      while (baseVue.super) {
        baseVue = baseVue.super
      }
      if (baseVue.config && baseVue.config.devtools) {
        // give a unique id to root instance so we can
        // 'namespace' its children
        if (typeof instance.__VUE_DEVTOOLS_ROOT_UID__ === 'undefined') {
          instance.__VUE_DEVTOOLS_ROOT_UID__ = ++rootUID
        }
        rootInstances.push(instance)
      }

      return true
    }
  })
  flush()
}
```

![image](https://user-images.githubusercontent.com/10419347/43268715-56b197c6-90bf-11e8-885a-19eb4eb72e32.png)

**Comment by ericcirone** [comment] 2018-07-26 14:34
@Akryum I do not have anything public that you could use to reproduce the issue. It's all private code. Sorry

**Comment by Akryum** [comment] 2018-07-26 17:38
@ericcirone Could you try this branch? https://github.com/vuejs/vue-devtools/tree/fix-duplicate-roots

**Comment by ericcirone** [comment] 2018-07-26 17:42
@Akryum yup give me a sec

**Comment by ericcirone** [comment] 2018-07-26 17:44
@Akryum yup that still works.
![image](https://user-images.githubusercontent.com/10419347/43278788-0dacdbe2-90da-11e8-8e3e-49c78fa554ae.png)

**Comment by Akryum** [comment] 2018-07-26 18:01
If you refresh you don't loose `<Root>`?

**Comment by ericcirone** [comment] 2018-07-26 18:03
@Akryum I just refreshed a bunch (both browser refresh and vue-devtools refresh button) All looks fine.

**Comment by Akryum** [comment] 2018-07-26 18:04
So it looks like it's definitively fixed this time! :smile_cat:

**Closed** 2018-07-26 18:03 UTC
Labels: bug, priority: high

**Comment by ridaamirini** [comment] 2018-07-29 16:36
How can i get the updated version for chrome ?

**Comment by sqal** [comment] 2018-09-10 11:16
I am still having this problem in 5.0.0 beta 1 :(

**Comment by powext** [comment] 2018-10-13 15:46
The problem persists in 4.1.5 beta :(
