### ISSUE TITLE
[Firefox] Vue detected but DevTools tab not added

### ISSUE THREAD

**Issue by Kovensky** [vuejs/vue-devtools#403] opened 2017-08-28 02:47 UTC
The addon icon lights up with the message `Vue.js is detected on this page. Open DevTools and look for the Vue panel.`; however, opening up the panel does not show the Vue panel. The Vue panel is also not hidden, as it cannot be chosen for hiding in the "Developer Tools installed by add-ons" settings either.

To be sure, the console also has the `"You are running Vue in development mode. (...)"` message from Vue, so the page I am trying to debug is also running in development mode.

Firefox 55.0.3, Vue DevTools 3.1.6 (both fresh installs).

**Comment by caugner** [comment] 2017-08-30 16:39
Do you have the developer tools open at the bottom or at the side or in a separate window? The latter didn't work for me either.

**Comment by caugner** [comment] 2017-08-30 16:40
Duplicate of #366

**Closed** 2017-08-30 17:17 UTC

**Comment by JosephNC** [comment] 2018-06-23 11:34
For me, it works after closing and opening the developer tools.

**Comment by femaimi9527** [comment] 2020-01-06 14:44
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

**Comment by jerrychong25** [comment] 2020-06-04 07:55
For me, I managed to make it working by:
1. Close all Vue.js websites
2. Close DevTools
3. Disable Vue.js DevTools add-on
4. Enable DevTools again
5. Open DevTools
