### ISSUE TITLE
Tab position is not preserved in Chrome

### ISSUE THREAD

**Issue by skollro** [vuejs/vue-devtools#793] opened 2018-10-02 08:20 UTC
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 69, MacOS 10.14

### Steps to reproduce
1. Open Vue Devtools
2. Reorder tabs in Chrome DevTools
3. Close Chrome DevTools
4. Reopen Chrome DevTools.

### What is expected?
Tab position of Vue Devtools is preserved.

### What is actually happening?
Tab position of Vue Devtools is NOT preserved.

**Comment by kaungmyatlwin** [comment] 2018-10-02 09:45
See #441 .

**Comment by Akryum** [comment] 2018-10-02 12:07
Duplicate of #441

**Closed by Akryum** 2018-10-02 12:07 UTC
