### ISSUE TITLE
Event listener error

### ISSUE THREAD

**Issue by qiutuleng** [vuejs/vue-devtools#559] opened 2018-01-25 02:51 UTC
### Version
4.1.0

### Browser and OS info
Chrome 63.0.3239.132 (Official Build) (64-bit) / Ubuntu 16.04

### Steps to reproduce
Enable the Vue.js devtools extension, and then right click on the page using the vue framework

### What is expected?
Don't throw error.

### What is actually happening?
Each time right-click on the page, chrome throws an error.
If I disable the extension there will be no error.

![error_in_console](https://user-images.githubusercontent.com/30284139/35368235-569885a6-01bd-11e8-8179-e07e5c6964af.png)
![error_detail](https://user-images.githubusercontent.com/30284139/35368239-58132c42-01bd-11e8-8d61-8a675359bb0b.png)

**Comment by rhinel** [comment] 2018-01-25 03:24
一样的问题，任何右键点击都报错

**Comment by luck2011** [comment] 2018-01-25 05:27
+1, keep getting the same error after updating chrome devTools!

**Comment by tzurbaev** [comment] 2018-01-25 05:50
Same on Google Chrome 64.0.3282.119 (Official Build) (64-bit), vue-devtools v4.1.0, Ubuntu 17.10.

**Comment by BlitZz96** [comment] 2018-01-25 09:07
#553 @Akryum

**Comment by DavidDeSloovere** [comment] 2018-01-25 09:16
Seems to ba ixed already. Just not released yet.
https://github.com/vuejs/vue-devtools/issues/514

**Comment by Akryum** [comment] 2018-01-25 09:19
Duplicate of #514

**Closed by Akryum** 2018-01-25 09:19 UTC
