### ISSUE TITLE
Crash when loading web page

### ISSUE THREAD

**Issue by paulrosen** [vuejs/vue-devtools#776] opened 2018-09-17 15:13 UTC
### Version
5.0.0-beta.3

### Browser and OS info
Chrom 69 / El Capitan

### Steps to reproduce
Just go to my web page in dev mode with the vue-devtools enabled.

### What is expected?
Everything to work like it did in version 4.

### What is actually happening?
Get a javascript error in a getter because it is called before initialization.

---
This might be more of a clue about what is going on. In my app, one of the first things I do is set the `router` property in my state. I do that here:
```
new Vue({
  ...
  created: function() {
    store.dispatch('setRouter', router);
  }
```

With the new version of the vuetools, `rootGetters.router` is null and causes a crash in one of my getters and the entire initialization stops.

**Comment by Akryum** [comment] 2018-09-17 15:53
@simplesmiler Could this come from the early Vuex clone?

**Comment by unclejustin** [comment] 2018-09-17 16:40
FWIW I was having a similar problem. Hard crash could not load my site when vuex hit this code `devtoolHook.emit('vuex:init', store);` I disabled vue-devtools and the site worked fine. Strangely I re-enabled vue-devtools and the site still works.

**Comment by cpepin** [comment] 2018-09-17 18:26
It seems to be related to the beta release.  I don't see the error when I have the production dev tools running.

**Comment by ryanlynch717** [comment] 2018-09-18 15:13
I'm seeing the same thing using vue-devtools 5.0.0-beta.3 and Chrome 69.0.3497.100. Vuex getter rootState.route is undefined.

I'm also intermittently seeing another error: __VUE_DEVTOOLS_UID__ of undefined in vue-devtools on the 4.1.5 beta version

**Comment by siberiadev** [comment] 2018-09-22 00:41
Hey, I've got the same problem here. Just upgrade to v5beta, and got "Cannot read property 'getters' of undefined" in Chrome JS console. 
![image](https://user-images.githubusercontent.com/42664395/45911251-57355780-be43-11e8-8d4f-c6905307af7c.png)

**Comment by ryanlynch717** [comment] 2018-09-24 15:10
I got it to work by removing the Vue devtools plugin(s) and reinstalling them on the latest (fresh install) version of Chrome.

**Comment by neeravp** [comment] 2018-10-01 13:18
I am facing vue devtools crashing problem even without using vuex. I an hour of coding it crashes atleast 8-10 times.

**Comment by Ben52** [comment] 2018-10-04 18:48
I'm getting an error with the new dev tools using Vuex and vuex-router-sync.
Its crashing on a getter: 
```
inBookingView(state) {
            return state.route.name === 'bookings';
        }
```
with an error: `Cannot read property 'name' of undefined`, 
it works fine with Vue devtools 4.

**Comment by mikerockett** [comment] 2018-10-10 04:06
In my case:

```
Uncaught TypeError: Cannot read property '_modulesNamespaceMap' of undefined
    at getModuleByNamespace (app.js?id=411dba539e4fd3da7533:174959)
    at Vue.mappedGetter (app.js?id=411dba539e4fd3da7533:174892)
    at Watcher.get (app.js?id=411dba539e4fd3da7533:166214)
    at Watcher.evaluate (app.js?id=411dba539e4fd3da7533:166321)
    at Proxy.computedGetter (app.js?id=411dba539e4fd3da7533:166579)
    at l (<anonymous>:1:1915)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at i (<anonymous>:1:2190)
    at Object.n.once.t (<anonymous>:1:2698)
```

**Comment by larsmars** [comment] 2018-10-18 08:51
I have the same described here: https://github.com/vuejs/vue-devtools/issues/775

**Comment by trollderius** [comment] 2018-12-12 12:21
This is a big thing for me, getters could be collapsed and disabled by default and call them all on expand.

**Comment by Akryum** [comment] 2019-10-28 13:59
Duplicate of #775

**Closed by Akryum** 2019-10-28 13:59 UTC
