### ISSUE TITLE
Hook into Cypress e2e Test Rig

### ISSUE THREAD

**Issue by nothingismagick** [vuejs/vue-devtools#687] opened 2018-05-20 09:02 UTC
### What problem does this feature solve?
I would like to have access to the vue devtools in Cypress, but it is not available when using the chrome version (even though I have been able to "successfully" install the devtools as a chrome extension).

### What does the proposed API look like?
@brian-mann from the Cypress dev team wrote this on my [issue over there](https://github.com/cypress-io/cypress/issues/1742)
> Vue isn't finding it because it's looking at window.top which is Cypress -> not your App. Instead you can just use your app itself (or cypress code) to point vue to window.top so that the extension finds it. It may be as simple as window.top.vue = window.vue but I'd have to dig in.

**Comment by superMDguy** [comment] 2018-05-24 21:09
I'm pretty sure this is the same issue as #353

**Comment by Akryum** [comment] 2018-07-25 13:58
Duplicate of #353

**Closed by Akryum** 2018-07-25 13:58 UTC
