### ISSUE TITLE
Vuex two-way computed properties not updating

### ISSUE THREAD

**Issue by kiwina** [vuejs/vue-devtools#440] opened 2017-10-23 17:47 UTC
when tracking changes is on it updates values else it dosn't, but when i check the value by printing it in the console its correct.
the code
```
limitRowsAmount: {
      get () {
        return this.$store.state.config.limitRowsAmount
      },
      set (value) {
        this.$store.commit('limitRowsAmount', value)
      }
    }


```
the mutation
```
    limitRowsAmount (state, data) {
      state.config.limitRowsAmount = data
    }
```
the template
```
<input type="text" v-model="limitRowsAmount">
```

**Comment by posva** [comment] 2017-10-23 19:48
duplicate of #393

**Closed by posva** 2017-10-23 19:48 UTC
