### ISSUE TITLE
Crash When Dev Tools Open on non-Vue Application

### ISSUE THREAD

**Issue by mlturner88** [vuejs/vue-devtools#551] opened 2018-01-24 20:02 UTC
### Version
4.1.0

### Browser and OS info
Chrome v64.0.3282.119 (64-bit) / Windows 10

### Steps to reproduce
1. Navigate to non-Vue application with dev tools enabled (e.g. msn.com)
2. Open Chrome developer tools for site
3. Right-click an element on the page

### What is expected?
Right-click context menu appears as normal.

### What is actually happening?
Developer Tools are hitting an exception in the Vue dev tools extension code. If you continue the breakpoint the context menu does appear.

## Console Error

```javascript
Uncaught ReferenceError: o is not defined
    at HTMLDocument.document.addEventListener.t (<anonymous>:1:784)
```

## Code Where Error Occurs

```javascript
document.addEventListener("contextmenu", t=>{
        const n = t.target;
        if (n) {
            const t = Object(o.a)(n);
            if (t)
                return e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = !0,
                void (e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = t)
        }
        e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = null,
        e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = null
    }
```

**Comment by Akryum** [comment] 2018-01-24 20:36
Duplicate of #514

**Closed by Akryum** 2018-01-24 20:36 UTC
Labels: duplicate
