### ISSUE TITLE
Enable devtools in prod. mode

### ISSUE THREAD

**Issue by fguisso** [vuejs/vue-devtools#1247] opened 2020-07-28 21:54 UTC
### Version
6.0.0-beta.1

### Browser and OS info
Firefox

### Steps to reproduce
https://codedharma.com/posts/force-vue-devmode/
Tested in various vue apps without `devetools = true`

### What is expected?
Don't enable devtools

### What is actually happening?
devtools works

---
This issue is just to clarify if devtools needs to work or not in prod. mode.

Questions that we need to awnser:

- Why disable devtools in prod. mode?
- Today we can disable in prod. mode but there is a bypass with a single variable, this means that the API of devtools is loaded every time, is this correct?

**Comment by iChenLei** [comment] 2021-01-21 15:04
Vue3 change the devtools logic flow, look for this comment https://github.com/vuejs/vue-devtools/issues/1308#issuecomment-764688863

### Summary
Vue2 have this problem, Vue3 have no problem. And I also don't know why we need disbale devtools in production, React didn't do it but nothing happened. 

>Today we can disable in prod. mode but there is a bypass with a single variable, this means that the API of devtools is loaded every time, is this correct?

```js
   var devtools = inBrowser && window.__VUE_DEVTOOLS_GLOBAL_HOOK__;

  if (devtools) { ***
```
me: If user don't install vue-devtools, this check will failed, don't need worry it。If you care about security just remember **Frontend code is untrustworthy , Backend need do strictly auth check**

**Comment by Akryum** [comment] 2021-01-29 11:42
Duplicate of #1321

**Closed by Akryum** 2021-01-29 11:42 UTC
