### ISSUE TITLE
Don't work in Firefox Nightly

### ISSUE THREAD

**Issue by justerest** [vuejs/vue-devtools#399] opened 2017-08-23 19:03 UTC
Firefox 57.0
Linux Debian 9

**Comment by shintaro4** [comment] 2017-08-24 04:15
**debugging#addons console**

```
Unix error 2 during operation DirectoryIterator.prototype.next on file /Users/***/Library/Application Support/Firefox/Crash Reports/pending (No such file or directory)  CrashSubmit.jsm:541
	CrashSubmit_pendingIDs resource://gre/modules/CrashSubmit.jsm:541:7
	throw self-hosted:1204:9
Unix error 2 during operation DirectoryIterator.prototype.next on file /Users/***/Library/Application Support/Firefox/Crash Reports/pending (No such file or directory)  ContentCrashHandlers.jsm:670
	checkForUnsubmittedCrashReports resource:///modules/ContentCrashHandlers.jsm:670:7
	throw self-hosted:1204:9
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://addons-discovery.cdn.mozilla.net 'sha256-DiZjxuHvKi7pvUQCxCVyk1kAFJEUWe+jf6HWMI5agj4='”). normal:1
Use of getAttributeNode() is deprecated. Use getAttribute() instead. disco-f05a47a21fad9eacedf5.js:1:662126
TelemetryStopwatch: key "TELEMETRY_PENDING_LOAD_MS" was already initialized TelemetryStopwatch.jsm:343
	start resource://gre/modules/TelemetryStopwatch.jsm:343:7
	start resource://gre/modules/TelemetryStopwatch.jsm:139:12
	loadPendingPing resource://gre/modules/TelemetryStorage.jsm:1343:5
	InterpretGeneratorResume self-hosted:1280:8
	next self-hosted:1187:9
TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "TELEMETRY_PENDING_LOAD_MS", key: "null"  TelemetryStopwatch.jsm:363
	timeElapsed resource://gre/modules/TelemetryStopwatch.jsm:363:9
	finish resource://gre/modules/TelemetryStopwatch.jsm:382:17
	finish resource://gre/modules/TelemetryStopwatch.jsm:225:12
	loadPendingPing resource://gre/modules/TelemetryStorage.jsm:1396:5
	InterpretGeneratorResume self-hosted:1280:8
	next self-hosted:1187:9
```
Firefox Nightly 57.0a1 (2017-08-23) (64-bit)
macOS Sierra version 10.12.6

**Comment by caugner** [comment] 2017-08-30 16:37
I can confirm the issue on Linux and Windows.

**Comment by caugner** [comment] 2017-08-30 16:41
Potential duplicate of #366

**Closed** 2017-08-30 17:17 UTC
