### ISSUE TITLE
Keyboard navigation in Inspector

### ISSUE THREAD

**Issue by ladariha** [vuejs/vue-devtools#1438] opened 2021-05-13 07:00 UTC
### What problem does this feature solve?
In Inspector, when I click on some displayed component in the component tree, it would be really useful to have keyboard navigation:
- up/down would move to next/previous component
- left would collapse current branch (subtree  / component)
- right would expand the current component

The reason is it is (subjective matter) quicker to just click on the component and use keyboard to control the tree instead of moving mouse.

### What does the proposed API look like?
It is internal vue-devtools change, no public API needed

**Comment by Akryum** [comment] 2021-05-13 11:00
Duplicate of #1430

**Closed by Akryum** 2021-05-13 11:00 UTC
