### ISSUE TITLE
No components/App detected

### ISSUE THREAD

**Issue by hbshvn** [vuejs/vue-devtools#1349] opened 2021-01-17 12:46 UTC
### Version
6.0.0-beta.3

### Browser and OS info
Chrome 87 / Mac OS Catalina

### Steps to reproduce
- Install devtools Beta 6.0.0.3
- Start Vue 3 application
- get "Application detected" status from Vue devtools
- get "connected" status in console

### What is expected?
- I also see components tree inside of Vue devtools

### What is actually happening?
I see only search bar with "Find components..." and nothing else

**Comment by hbshvn** [comment] 2021-01-17 13:38
Update: when i open the same Vue Project in a devtool on my virtual Windows 10 Machine everything works fine

**Comment by mathiash98** [comment] 2021-01-18 08:35
Seems like the same issue as the issue I reported at #1341

**Comment by hbshvn** [comment] 2021-01-18 09:11
> Seems like the same issue as the issue I reported at #1341
> 
> Does firefox work for you?

Yes I use firefox for vue development now, but not really enjoy it(

**Comment by thespragg** [comment] 2021-01-21 17:02
I'm also having this issue, chromium 83.0.4103.116 on pop!_os 20.10

**Comment by Akryum** [comment] 2021-01-29 10:51
Could you try closing the devtools, refreshing the page and opening the devtools again? Also please make sure you don't have the stable devtools enabled at the same time.

**Comment by mathiash98** [comment] 2021-01-29 10:56
> Could you try closing the devtools, refreshing the page and opening the devtools again? Also please make sure you don't have the stable devtools enabled at the same time.

Doesn't help for me at least

**Comment by Akryum** [comment] 2021-01-29 11:22
No additional errors printed in the console?

**Comment by mathiash98** [comment] 2021-01-29 11:24
> No additional errors printed in the console?

See https://github.com/vuejs/vue-devtools/issues/1341 for my bug report with all information I get.

**Comment by Akryum** [comment] 2021-01-29 11:25
Let's continue here then.

Duplicate of #1341

**Closed by Akryum** 2021-01-29 11:25 UTC
Labels: v6

**Comment by mathiash98** [comment] 2021-02-01 09:29
@thespragg @kaz-212 @hbshvn https://github.com/vuejs/vue-devtools/issues/1341#issuecomment-770706458

^^ Check if you have third party cookies disabled. I enabled it, then it works

**Comment by kaz-212** [comment] 2021-02-01 11:27
Thanks @mathiash98. It now works for me !
