### ISSUE TITLE
Icon missing in Firefox Developer Edition

### ISSUE THREAD

**Issue by AdrianDuan** [vuejs/vue-devtools#381] opened 2017-07-29 14:39 UTC
My environment
Browser: Firefox Developer Edition 55.0b13 (64 bit)
Vue.js Devtools: 3.1.6
<img width="1627" alt="_ _vue_js" src="https://user-images.githubusercontent.com/26034046/28745632-c53eb6fc-74ae-11e7-986a-19f34383877a.png">

**Comment by caugner** [comment] 2017-08-30 16:42
Duplicate of #366

**Comment by posva** [comment] 2017-08-30 17:17
Thanks for signaling it @caugner  🙂

**Closed by posva** 2017-08-30 17:17 UTC

**Comment by femaimi9527** [comment] 2020-01-06 14:44
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.
