### ISSUE TITLE
Vuex Getters overflow:visible and display glitch after first mutation

### ISSUE THREAD

**Issue by gterras** [vuejs/vue-devtools#558] opened 2018-01-25 01:48 UTC
### Version
4.1.0

### Browser and OS info
Linux Chrome 63 / Firefox 57 

### Steps to reproduce
- Open dev tool 
- Select Vuex 
- Trigger a mutation 
- Click on Getters on right panel 

### What is expected?
A correct display of Getters content 

### What is actually happening?
Content is duplicated, element overflows even when collapsed, two unrelated double quotes are displayed. 

---
Display was correct in previous version. Thanks !

**Comment by Akryum** [comment] 2018-01-25 09:30
Are you storing HTML strings in the store?

**Comment by gterras** [comment] 2018-01-25 09:38
Yes I am, I saw the ticket but wasn't sure it was related. Thanks !

**Comment by Akryum** [comment] 2018-01-25 09:50
Duplicate of #555

**Closed by Akryum** 2018-01-25 09:50 UTC
