### ISSUE TITLE
Vue devtools crashes/freezes on page refresh

### ISSUE THREAD

**Issue by scootstah** [vuejs/vue-devtools#595] opened 2018-01-30 17:37 UTC
### Version
4.1.2

### Browser and OS info
Google Chrome Version 64.0.3282.119 / Debian 8

### Steps to reproduce
1. Open app with VueJS
2. Open devtools, go to Vue tab
3. Refresh web page

### What is expected?
Vue devtools reloads and continues to function

### What is actually happening?
Vue devtools freezes. The components and Vuex tabs are stuck in their last state, and you cannot interact with any part of the Vue devtools. You have to close devtools completely and re-open them every time you refresh the page.

---
I noticed Vue devtools was just updated yesterday, and it is now broken for me today.

**Comment by Akryum** [comment] 2018-01-30 17:52
Duplicate of #588

**Closed by Akryum** 2018-01-30 17:52 UTC
