### ISSUE TITLE
Inspect DOM doesn't seem to do anything

### ISSUE THREAD

**Issue by sidecut** [vuejs/vue-devtools#370] opened 2017-07-09 17:00 UTC
The "Inspect DOM" link doesn't seem to do anything at all. The source code implies that perhaps it uses the Chrome devtools (?) API to select the DOM element of the currently selected Vue component, but nothing happens.

If I select a random DOM element on my own that does not correspond to any Vue component, and then, from the VueJS extension, select a Vue component from the left pane and then click "Inspect DOM" in the right pane,  then go back to the Elements tab, the currently selected DOM element hasn't changed at all.

To eliminate interference from other extensions, I created a new Chrome user profile, added Vue-devtools, disabled all other extensions, and tried it. The "Inspect DOM" button still doesn't do anything.

I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit), and Vue.js devtools Version: 3.1.4.

**Comment by posva** [comment] 2017-07-14 17:02
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.

**Comment by sidecut** [comment] 2017-07-14 17:09
I could create a sample html file on gist to reproduce the problem. It shouldn't take much -- it never works, not even intermittently.

**Comment by posva** [comment] 2017-07-14 17:11
Don't worry, I verified it that's why I marked it as a regression 🙂

**Comment by Akryum** [comment] 2018-03-16 11:44
Please reopen if you can reproduce the issue with the latest versions of Chrome and Vue devtools.

**Closed by Akryum** 2018-03-16 11:44 UTC
Labels: cannot reproduce, regression

**Comment by yringler** [comment] 2018-04-24 20:11
It's not working for me either.
Is it working for anyone?

**Comment by nolde** [comment] 2019-02-04 04:07
Does not work for me as well, Windows 10 x64, Chrome 72.0.3626.81 x64 (I have it on auto-update and it never worked for me in any version).
