### ISSUE TITLE
"ReferenceError: o is not defined" in the console

### ISSUE THREAD

**Issue by MaskeZen** [vuejs/vue-devtools#567] opened 2018-01-25 15:45 UTC
### Version
4.1.0

### Browser and OS info
Firefox 58.0 (64-bit) and Firefox dev 59.0b3 (64-bit) / Windows 10

### Steps to reproduce
Right click on any page and the console display the error.

### What is expected?
nothing

### What is actually happening?
ReferenceError: o is not defined   index:1:774

**Comment by Akryum** [comment] 2018-01-25 15:48
Duplicate of #514

**Closed by Akryum** 2018-01-25 15:48 UTC

**Comment by MaskeZen** [comment] 2018-01-25 15:59
Agree! I updated from version 4.1.0 to 4.1.1 and this fixed it.
Thanks!
