### ISSUE TITLE
[Firefox] Cannot scroll in panes

### ISSUE THREAD

**Issue by retrocede** [vuejs/vue-devtools#368] opened 2017-07-07 16:48 UTC
In FF 54.0.1 on Mac OS, none of the panes allow vertical scrolling once the content is outside of the view. This includes:

- Components
- Mutations
- Store

**Comment by jk3us** [comment] 2017-07-14 18:59
I think this is a dupe of #355, which is closed, but the fix isn't available on AMO yet.

**Comment by posva** [comment] 2017-07-17 12:00
@retrocede can you try building the plugin locally? If it's still happening, I'll reopen this

**Closed by posva** 2017-07-17 12:00 UTC

**Comment by urkle** [comment] 2017-07-25 01:58
@posva I built and tested master on FF 54.0.1 on macOS Sierra and everything works fine (scrolling works great)..   Is there any status on  when the next AMO build will be released?  Do I need to poke someone at Mozilla to get it reviewed faster?
