### ISSUE TITLE
Error `Uncaught TypeError: Cannot read property 'type' of null` is happening when click some of compoents

### ISSUE THREAD

**Issue by ryutamaki** [vuejs/vue-devtools#537] opened 2018-01-21 07:23 UTC
### Version
4.0.0

### Browser and OS info
Version 63.0.3239.132（Official Build） （64bit）

### Steps to reproduce
1. Open inspector
2. Click some of the component

### What is expected?
vue-devtools shows me information of selected components

### What is actually happening?
```
backend.js:1 Uncaught TypeError: Cannot read property 'type' of null
    at VM7093 backend.js:1
    at x (VM7093 backend.js:1)
    at t.a (VM7093 backend.js:1)
    at Object.y (VM7093 backend.js:1)
    at e (VM7093 backend.js:1)
    at e (VM7093 backend.js:1)
    at e (VM7093 backend.js:1)
    at e (VM7093 backend.js:1)
    at Object.t.stringifyStrict (VM7093 backend.js:1)
    at Object.t.stringify (VM7093 backend.js:1)
```

**Comment by filipsobol** [comment] 2018-01-21 11:57
I have the same issue, both on Chrome and FF.

**Comment by Akryum** [comment] 2018-01-21 12:05
Duplicate of #499, see https://github.com/vuejs/vue-devtools/issues/499#issuecomment-357506247

**Closed by Akryum** 2018-01-21 12:05 UTC
