### ISSUE TITLE
Vue.js not detected but Vue tab in inspector is OK

### ISSUE THREAD

**Issue by simenko** [vuejs/vue-devtools#704] opened 2018-07-11 07:31 UTC
### Version
4.1.4

### Browser and OS info
Version 67.0.3396.99 (Official Build) (64-bit)    Ubuntu 16.04

### Steps to reproduce
Bug appears to be intermittent, it is not reproducing consistently

1. Open a page with vue.js app. 
2. Open inspector

### What is expected?
Right mouse button menu should have 'inspect vue component' item, vue devtools logo in the toolbar should be green

### What is actually happening?
There is no 'inspect vue component' menu item, vue logo is grey, it shows 'Vue.js not detected' tooltip on click, but there is active vue tab in the inspector, I can use all of the tools.

**Comment by Akryum** [comment] 2018-07-25 14:39
Duplicate of #525

**Closed by Akryum** 2018-07-25 14:39 UTC
Labels: bug, need repro
