### ISSUE TITLE
BUG? Unchecked runtime.lastError: Cannot find menu item with id vue-inspect-instance

### ISSUE THREAD

**Issue by xuejiangjun** [vuejs/vue-devtools#902] opened 2019-03-15 05:03 UTC
### Version
4.1.5-beta.1

### Browser and OS info
chrome73.0.3683.75

### Steps to reproduce
I install vue-devtools from chrome store, and in chrome devtools I drag Vue from last to second place, that is happened. and I could not find Vue devtools item anymore, and it has a error in extensions:Unchecked runtime.lastError: Cannot find menu item with id vue-inspect-instance,but my other project could find Vue devtools in chrome devtools.
![TIM截图20190315130020](https://user-images.githubusercontent.com/16046545/54409598-a4272600-4722-11e9-8b64-9f6b4028c465.png)

### What is expected?
Vue devtools should in chrome devtools

### What is actually happening?
Vue devtools not in chrome devtools

**Comment by Kameals** [comment] 2019-03-17 13:48
Hi, xuejiangjun.
It was similar to my case. 
Did you install the vuejs devtools while you make the app? 
In my case, I restart the vuejs app project and solved.

**Comment by xuejiangjun** [comment] 2019-03-17 14:33
> Hi, xuejiangjun.
> It was similar to my case.
> Did you install the vuejs devtools while you make the app?
> In my case, I restart the vuejs app project and worked.

I restart and reinstall it  many times but dosent work, so I give up. I do not know what is the reason, maybe it is chrome's bug.

**Comment by renyuns** [comment] 2019-03-17 14:56
i have the same problem, same Devtools version,same chrome version, (and my computer is mac pro). 
Has your problem been solved?

**Comment by xuejiangjun** [comment] 2019-03-17 15:00
> i have the same problem, same Devtools version,same chrome version, (and my computer is mac pro).
> Has your problem been solved?

no

**Comment by renyuns** [comment] 2019-03-17 15:00
![image](https://user-images.githubusercontent.com/22095724/54493213-32103600-4908-11e9-967c-3f0af7137326.png)
![image](https://user-images.githubusercontent.com/22095724/54493226-59ff9980-4908-11e9-9178-5879739eac0a.png)
![image](https://user-images.githubusercontent.com/22095724/54493241-7f8ca300-4908-11e9-8ca3-049e3a268eca.png)

**Comment by renyuns** [comment] 2019-03-17 15:02
![image](https://user-images.githubusercontent.com/22095724/54493259-ae0a7e00-4908-11e9-8fe4-49593bef45e3.png)

**Comment by xuejiangjun** [comment] 2019-03-17 15:03
@renyuns 我复现一下这个问题：我把vue-devtools安装之后，把它从最后拉到前面 console后面，然后一会就不起作用了，我就关了F12重新打开，然后发现Vue没有了，不管怎么重装活着是禁用开启，都是报这个错误，估计是谷歌或者是插件的问题。

**Comment by renyuns** [comment] 2019-03-17 15:10
@xuejiangjun 那就不知道了🤣

**Comment by Akryum** [comment] 2019-03-20 16:12
Duplicate of #629

**Closed by Akryum** 2019-03-20 16:12 UTC
