### ISSUE TITLE
Can't see Vuex Store log (mutations for example)

### ISSUE THREAD

**Issue by alexanderdeabreuwannme** [vuejs/vue-devtools#1407] opened 2021-04-17 14:18 UTC
### Version
6.0.0-beta.7

### Browser and OS info
Chrome (no idea about version)

### Steps to reproduce
1. Open your project
2. Access to dev tools

### What is expected?
Show vuex store logs when something happened, like a mutation.

![image](https://user-images.githubusercontent.com/81359416/115116175-9646cd80-9f98-11eb-870e-7108a7d42427.png)

### What is actually happening?
Nothing
![image](https://user-images.githubusercontent.com/81359416/115116162-8f1fbf80-9f98-11eb-8d59-aea8ace29e0f.png)

---
-

**Comment by Akryum** [comment] 2021-04-17 15:27
Duplicate of #1268

**Closed by Akryum** 2021-04-17 15:27 UTC
