### ISSUE TITLE
DevTools for Chrome Extension Development.

### ISSUE THREAD

**Issue by IORoot** [vuejs/vue-devtools#120] opened 2016-06-30 09:08 UTC
Hi there, 
I'm building a chrome extension (a browser action) and including VUE.js into it. However, whenever I inspect the code for the browser action your VUE DevTools does not appear in the list of tabs. 
Perhaps I've not enabled it properly, but is this something I should be able to do? or is this limitation?

VUE Devtools opens up correctly in the normal devtools window by the way. It's only in the instance of the browser extension. Any suggestions?
Many thanks!

**Comment by 74sharlock** [comment] 2016-07-13 06:02
i have a same issue.

**Comment by warrantica** [comment] 2016-07-17 06:06
Same for me as well. It seems that the dev tool works with `http://` (or `file://` if "Allow access to file URLs" is selected), but extension pages are served over `chrome-extension://` so that may have something to do with it.

**Comment by etiennemarais** [comment] 2016-07-28 18:40
Same problem, did a fresh install of laravel 5.3 today, Added the vue devtools to chrome `Version 51.0.2704.103 (64-bit)` And it doesn't show up even when enabled. Not sure if I am doing something wrong but any advise would be greatly appreciated.

**Comment by alexander-ossur** [comment] 2016-08-15 00:14
Same story. Yet I did not test with usual pages by http:// or file://

**Comment by SoullessWaffle** [comment] 2017-01-31 16:17
Related: #130

**Comment by posva** [comment] 2017-02-15 12:17
Maybe we could learn from redux or react devtools. I think they support this. https://github.com/zalmoxisus/redux-devtools-extension/blob/v2.2.1/src/browser/extension/inject/index.js

I don't know if it's related to remote debugging

**Comment by xralphack** [comment] 2017-05-26 16:21
+1

**Comment by Folyd** [comment] 2017-06-04 09:24
Sounds so bad that the "chrome://" pages didn't get support 😭 😞

**Comment by fremdev** [comment] 2017-06-27 10:22
Any progress or workaround?

**Comment by dgpgdev** [comment] 2017-07-05 16:01
+1

**Comment by Banou26** [comment] 2017-07-13 14:23
Can we just not simply use chrome://flags/#extensions-on-chrome-urls with a permission request on chrome:// URLs here https://github.com/vuejs/vue-devtools/blob/master/shells/chrome/manifest.json#L31 ?

**Comment by yaotian** [comment] 2017-08-25 07:56
+1

**Comment by posva** [comment] 2017-08-25 08:29
Please, don't comment to say _+1_, use the reaction feature 🙂

**Comment by posva** [comment] 2017-08-25 08:30
Please don't comment to say _+1_, use the reaction feature 🙂

**Comment by yesm1994** [comment] 2017-09-12 07:33
any progress?

**Comment by avrtau** [comment] 2017-10-29 21:59
This worked for me:
[https://github.com/vuejs/vue-devtools/issues/62#issuecomment-21532515](https://github.com/vuejs/vue-devtools/issues/62#issuecomment-215325153)

**Comment by andreiglingeanu** [comment] 2017-11-18 12:17
Hey @posva, yes, that is the only way to go. Specifically because [`content_scripts`](https://github.com/vuejs/vue-devtools/blob/472f3c67200bd70853bc5a93c401cbe9b46fc00f/shells/chrome/manifest.json#L37-L48) defined in chrome shell won't ever run in the context of a Web Extension page.

Sadly, that's something that people from [react-devtools are also struggling with](https://github.com/facebook/react-devtools/issues/91#issuecomment-341488301). Tough `redux-devtools` managed to solve that by instructing extensions developers to manually include a specially prepared script that will trigger the devtools initialization in the context of a `chrome://*` page.

Maybe that's something we can learn from?

**Comment by michalsnik** [comment] 2018-01-04 01:23
I also think we should create electron based devtools package that will allow remote debugging whatever our users need.

**Comment by Akryum** [comment] 2018-01-04 03:12
Discussion on the Electron shell: #451, related PR: #452.

I think we can close this as a remote Electron shell would fix this.

**Closed by Akryum** 2018-01-04 03:12 UTC
Labels: discussion, feature request

**Comment by ppKrauss** [comment] 2018-03-09 14:50
**Is a bug**,  Chrome extension vue-devtools not detecting Vue.js

please see https://stackoverflow.com/q/49196181/287948

**Comment by zrshishir** [comment] 2018-03-19 04:20
I have faced same problem. Now I can see the vue tab in my console. I was using production version of vue now i am using vue developer version. It may help you.

**Comment by torarnv** [comment] 2018-03-24 12:13
This is still an issue. Using Vue in a Chrome extension, eg: `chrome-extension://<hash>/app.html`, results in `Vue.config.devtools` being true, but `devetools` is undefined, resulting in this message on every reload:

```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
```

The Vue devtools button is grayed ut, and says "Vue.js not detected" when clicking it.

**Comment by wujunchuan** [comment] 2018-03-27 09:14
@torarnv 's situation is the same to me.
I have set these steps:

1. open `chrome-extension://<hash>/app.html`
2. set ` Vue.config.devtools  ` to be true
3. grant `Vue Devtools` ext file access

**Comment by tyler36** [comment] 2019-03-08 02:07
@wujunchuan worked for me with Chrome 72.

After changing ```manifest.js```, I had to un-install / re-install extension to force the ```content_security_policy``` update

**Comment by theharshin** [comment] 2019-10-20 16:28
The separate electron shell works for popup pages & standalone pages. There is still no workaround for making vue-devtools work with content scripts. I'm developing an extension that injects a whole sidebar built with Vue. There is still no way of debugging that! 
I've created an issue with some more details here: https://github.com/vuejs/vue-devtools/issues/988
Kindly look into this please 😓

**Comment by rewbilldou** [comment] 2020-02-27 18:35
@wujunchuan 
I received an error message for localhost:8090

![image](https://user-images.githubusercontent.com/21068272/75475028-dee29800-594c-11ea-8b21-bf60562d9ba0.png)

**Comment by linkerGitHub** [comment] 2020-03-09 11:18
thanks for @wujunchuan 's idea, it inspired me. 
if you want to use devTools for **content script** of chrome extension, you can try this tricky way.

1.install vue-remote-devtools,
`npm install -g @vue/devtools`
2.run it in terminal
`vue-devtools`
3.send a GET request to get the script it provide and use eval to run it, like this:

```
// at your content script
const xhr = new XMLHttpRequest()
xhr.open('GET', 'http://localhost:8098/')
xhr.onload = function (x, e) {
  eval(x.currentTarget.responseText)
};
xhr.send();
```

4.reinstall extension and reload your page with extension.here is what it look like
![image](https://user-images.githubusercontent.com/15519222/76204557-902ddb80-6233-11ea-986a-6215a1f2f6f0.png)

**Comment by traxium** [comment] 2020-10-01 11:40
@linkerGitHub 
It's also possible to install `npm install --save-dev @vue/devtools` locally, start local `./node_modules/.bin/vue-devtools` and connect a content script to Vue DevTools without `<script src="http://localhost:8098"></script>` via:
```JavaScript
// content-script.js

import devtools from '@vue/devtools' // Make sure you import devtools before Vue, otherwise it might not work as expected.
import Vue from 'vue'

if (process.env.NODE_ENV === 'development') {
  devtools.connect(/* host, port */)
}
```
because Vue DevTools server doesn't return proper CORS headers for `xhr.open('GET', 'http://localhost:8098/')` and this GET request is [blocked](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches) by the latest version of Chrome:
>Access to XMLHttpRequest at 'http://localhost:8098/' from origin 'https://my.website.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by SlitiBrahim** [comment] 2021-03-30 10:14
I was using `vue x2.6` and `@vue/devtools` version `^6.0.0-beta.6` in a content-script chrome extension and that did not worked thent I replaced `@vue/devtools` with version `^5.3.4` and now it's working, I have my components displayed in the vuedevtools app !

**Comment by mitar** [comment] 2021-04-16 18:51
For v3 of chrome extension manifest, I had to use:

```
  "content_security_policy": {
    "extension_pages": "script-src 'self' http://localhost:8098; object-src 'self'"
  },
```

I had to remove `unsafe-eval` from the list.

But it does not really work for me, shell connects, but in the extension I get:

```
Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at registerAppJob ((index):1261)
Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at getComponentInstance ((index):1500)
    at Object.sendComponentTreeData ((index):1425)
    at Bridge.<anonymous> ((index):1715)
    at Bridge.emit ((index):11402)
    at Bridge._emit ((index):3561)
    at (index):3493
    at Array.forEach (<anonymous>)
    at (index):3493
    at Socket.<anonymous> ((index):15309)
    at Socket.../../node_modules/component-emitter/index.js.Emitter.emit ((index):7395)
```

**Comment by lhermann** [comment] 2021-04-18 10:47
@mitar this happens because you are using vue-devtools@6 with a VUE 2 app. Try `npm i -g @vue/devtools@5`.

**Comment by mitar** [comment] 2021-05-12 09:08
Thanks. I missed that in comments above.

**Comment by mellester** [comment] 2023-02-20 10:29
In MV3 I am unable to add  `unsafe-eval` to my 'content_security_policy' and it seems like devtool uses eval() in there injection script. 
I am gone try and sandbox my entire vue application and see if I can it then.

**Comment by krinteron** [comment] 2023-02-25 07:18
instead of connecting a remote script, you can go to http://localhost:8098 and download the content and then connect the local script. The problem is that there is an eval in the code, which cannot be included in the manifest v3 (except for the sandbox)
However, it is possible to build this script using the vue devtools sources electron app configuring webpack to not minify and evaluate files or just run in dev mode.

**Comment by mellester** [comment] 2023-02-28 09:53
> 

Would love a bit more details how you managed that?

**Comment by mellester** [comment] 2023-02-28 11:32
> > 
> 
> Clone the repository https://github.com/vuejs/devtools Go to packages/shell_electron directory In the webpack.config.js file, add these lines:
> 
> ```
> optimization: {
>   minimize: false,
> },
> devtool: false,
> ```
> 
> Execute commands in sequence: `npm run build` `npm run start`
> 
> And make a GET request to the address http://localhost:8098/ via postman, or in the browser, but copying the script only from the response
> 
> Next, this script must be saved to a js file and connected to the extension being developed.
> 
> ```
> <head>
>   <script src="dev-tool.js"></script>
> ```

Thank you.
Some notes for others. tested this on tag v6.5.0 And it works. In a MV3 chrome extension. 
`npm install` complains about dependences errors so I used `yarn` on the root git folder to install. then I could run '`npm run build` `npm run start` in the shell_electron directory. `minimize: false` seems to be not needed. at least on branch 6.5

I can add the below lines to my manifest.json. This means I do not have too use postman to save the script. Just make sure your final production step removes this line from the manifest. 
```
"content_security_policy": {
"extension_pages": "script-src 'self' http://localhost:8098; object-src 'self'"
```
