### ISSUE TITLE
Impossible to open Chrome console with ESC key

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-devtools#608] opened 2018-02-06 02:05 UTC
### Version
4.1.3

### Browser and OS info
Chrome 64 / macOS and Linux

### Steps to reproduce
1. Open a Vue app
2. Open DevTools
3. Hit ESC to open console

### What is expected?
Console would open

### What is actually happening?
Console opens then immediately closes again

**Comment by Akryum** [comment] 2018-02-06 09:04
Duplicate of #426

**Closed by Akryum** 2018-02-06 09:04 UTC
