### ISSUE TITLE
Where did vuex go?

### ISSUE THREAD

**Issue by sean-hill** [vuejs/vue-devtools#1365] opened 2021-02-15 21:52 UTC
### Version
6.0.0-beta.6

### Browser and OS info
Chrome / Mac

### Steps to reproduce
Open vue-devtools, where is Vuex?

### What is expected?
I expect to be able to see all of my state, and list of the mutations that happen like I used to in the previous vue devtools.

### What is actually happening?
I can't see my app state, only the state of vuex at a selected component level.

**Comment by Akryum** [comment] 2021-02-15 22:24
Duplicate of #1268

**Closed by Akryum** 2021-02-15 22:24 UTC
